### ISSUE TITLE
Modify copy constructors for utility types

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#1]
We other copy constructors and assignment on the following types

* datatyeps
* dataspaces
* and property lists

These classes have a slightly different copy semantics than node objects.

**Comment by martukas** [comment]
What do you mean by this? I could take care of this if you could explain it a bit more.

**Comment by eugenwintersberger** [comment]
Here some more detailed explanation. Every object in HDF5 is referenced by a handler which is wrapped by the `ObjectHandle` class. Every handle has a reference counter which manages its lifetime. The reference counting functionality is also managed by `ObjectHandle`. So currently when you copy a handle the value of the id is copied and the reference count increased. 
When the handle is destroyed (its destructor called) it calls the appropriated `close` function on its id value which decreases the reference count again. If the reference count of an object drops to zero it is eventually removed. 

Currently the copy semantics of all objects in the library follows the above rules (as they hold an instance of `ObjectHandl`). However, for *Datatype*, *Dataspace* and *property lists* this might not be the correct behavior. Each of these three types has a `H5Xcopy` function in the C-API which implements virtually a copy construction. I suggest that for theses three types we change the copying behavior to real copy construction. This would mean that we need to provide 

* a copy constructor
* maybe  a copy assignment operator

where both use the appropriate `H5Xcopy` function.

**Comment by martukas** [comment]
Thanks. I'll take care of this.

**Comment by martukas** [comment]
In the process of providing these implementations I have also:
1) Created extensive tests for base Datatype class, ensuring 94% coverage
2) Implemented the defined equality comparison operators for Datatype
Outstaning issues with Datatype
1) Can't seem to find a way to initialize Datatype to be of classes: bitfield, reference or time
2) If Class::NONE is a valid class, then the class function may never throw?
3) Does it need to be a switch tree if class has an underlying type? No automatic cast?
4) If we are avoiding get_, perhaps get_class() function should simply be class()
5) What's in namespace prefdefined_types at the bottom of Datatype.hpp ? Don't see these used anywhere?
6) Unit tests for Datatype now cover a lot of logic, but the way they are organized is messy. This could be improved.

**Comment by eugenwintersberger** [comment]
I am actually starting with implementing the Array and VLenArray datatype. This is definitely a good starting point  for strings as it is slightly easier. When doing this I will also update the documentation for datatypes and check their default behavior. There are certain things which are unclear ;)

**Comment by eugenwintersberger** [comment]
Concerning the types
* reference
* time
* bitfield 

I would suggest that they are not yet implemented.  I will ask Elena about this.

**Comment by martukas** [comment]
So it looks like Class can be cast directly from the underlying type, which has simplified the get_class() implementation significantly. Could even be flagged as noexcept.
Cleaned out the stuff in 5, and the ticket has been split for the other two types in question.
This should conclude things here.
