### ISSUE TITLE
Re-definition of "type" prevents compilation using clang on MacOSX

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#101]
This has already been fixed, see branch which I will push very soon.

**Comment by SkyToGround** [comment]
Based on #102 and #100, it appears that this fix for Clang also makes it not work under GCC and (presumably) Windows. Is that correct?

**Comment by eugenwintersberger** [comment]
Seems like. I am currently working on this. There seems to be some major mess with ObjectId which I would like to first with Martin on Windows and Linux. And then move on the Clang and OSX.

**Comment by eugenwintersberger** [comment]
Sorry, accidentally closed this.

**Comment by martukas** [comment]
Tested on OSX. Merged
