### ISSUE TITLE
Debian fix should fallback to find_package if it could not find the source files

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#104]
Currently the fix for Debian and Ubuntu throws a fatal error if the the distribution is not supported.
Instead it should fall back on find_package as a last resort.

**Comment by martukas** [comment]
Redefined this problem with the opposite logic. First find_package is attempted. If that fails, then, if additional conditions are met (i.e. appropriate distributions) then the fix is attempted.
