### ISSUE TITLE
Conan improvements to the build system

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#106]
I have struggled to get conan to work properly with the project. The current state is that it works under MacOSX (most of the time) see upcoming issue. It also appears to work on Centos 7.4. There are however linking problems under Ubuntu. I am making the changes available as a branch (_d22adc4_) here and I will let you do with the code what you will.

**Comment by martukas** [comment]
Merged master and it now appears to build on Jenkins. @SkyToGround , take a look again. Does this also help with conan? The Jenkinsfile doesn't seem to reference conan, so this is probably not relevant.

**Comment by martukas** [comment]
This is being superseded by work being done in #85 
I am merging this branch into issue_85
Ubuntu-related issues will be solved in other tickets & once we have Ubuntu nodes
