### ISSUE TITLE
DebianGTestFix.cmake is fragile

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#107]
I have been having several problems with *DebianGTestFix.cmake* when compiling h5cpp under Ubuntu. It should probably be modified to better deal with different Ubuntu based Linux distributions.

**Comment by eugenwintersberger** [comment]
Definitely. I simply have no idea how to do this :) As a matter of fact with the current implementation we would have to ask every Debian and Ubuntu version we are on and then pick the right source directory. I am open to any suggestion how to improve this.

**Comment by eugenwintersberger** [comment]
Can you have a look on the current implementation. Martin added a new approach which should work out of the box with local installations of gtest. Would this be sufficient. 
For Debian and Ubuntu I see no other way than to manually add support (which is as a matter of fact not a big deal at all).
