### ISSUE TITLE
Ubuntu nodes

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#115]
Now that containerized builds are mostly working (see changes in branch related to #84) we may consider also getting images for some ubuntu distros. My suggestion is the most recent LTS version, 16.4 and potentially the latest non-LTS or the previous LTS (14.4)?

**Comment by eugenwintersberger** [comment]
I guess we can safely omit 14.4 but we should definitely test always on the current Ubuntu release and the current LTS.

**Comment by martukas** [comment]
All that remains now is to provide support for latest non-LTS distro
