### ISSUE TITLE
Tests for Driver classes

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#120]
Coverage shows lack of tests for the driver classes

**Comment by eugenwintersberger** [comment]
Ist most probably does. I have no good idea how to test this. But this is a general problem. I was thinking to add some more general tests, you could call them *system integration tests* based on the examples.

**Comment by martukas** [comment]
This is now partially solved in #251 except for the DirectDriver class, which I can't even figure out how that gets enabled. Where does the precompiler flag for that come from? This driver might also be part of the answer to yuelong's problem? @eugenwintersberger any thoughts here?

**Comment by eugenwintersberger** [comment]
The H5_HAVE_DIRECT is defined (or undefined) in the HDF5 C header files. It seems that this driver is not always available so I added this preprocessor directive in order to avoid complications during the build if the driver does not exist. What problem of Yuelong are you actually referring to?

**Comment by eugenwintersberger** [comment]
As a matter of fact the direct flie driver is not always available and thus testing is rather difficult. So I close this issue for now.

**Comment by eugenwintersberger** [comment]
Have to add more test for drivers anyhow - reopen.

**Comment by eugenwintersberger** [comment]
Ok - we can definitely close this.
