### ISSUE TITLE
Change generated documents path

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#121]
Generated html is all mixed up with the build files, cmake lists, intermediate files, etc.. making us then copy and commit all this junk to the gh-pages branch.
Need to change generated docs output paths so that the html hierarchy is the website and nothing else.

**Comment by eugenwintersberger** [comment]
I see your points. Lets schedule this for the next release where I want to deal mainly with documentation.

**Comment by martukas** [comment]
Following the resolution or #187 , some things here are still outstanding. So, although the repo is no longer balooning out of proportion, I have had to use a few hacky steps in the deployment of docs, mainly these lines
```bash
                    sh 'find ./ -type d -name "CMakeFiles" -prune -exec rm -rf {} \\;'
                    sh 'find ./ -name "Makefile" -exec rm -rf {} \\;'
                    sh 'find ./ -name "*.cmake" -exec rm -rf {} \\;'
                    sh 'rm -rf ./_sources'
```
to clean out the stuff that comes with the ``doc/build directory``
I am not sure if there is a better way to avoid bringing this stuff along?
