### ISSUE TITLE
Implement hdf5::datatype::String

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#13]
We need to implement the String data type.

**Comment by martukas** [comment]
The basic parts are in place.
1. I have made size and set_size functions in Datatype virtual, and I override them for string. Prevents setting of size for variable-length strings, and likewise returns the variable-length constant when queried.
2. A few other Datatype parameters have some marginal significance to strings, but are actually also meaningful to floats and possibly others: order, precision, offset. They may be more wisely implemented in the superclass?
3. Default trait for std::string is variable-length datatype. This would seem to be ok, but IO tests show that this only works if string for reading into is presized. The read function might need to be somehow made smarter to resize strings?
4. Can't get IO with fixed length strings to work at all. The function for reading attribute with custom datatype is not implemented.
5. Tests are ready for std::wstring, std::u16string, std::u32string, but how these are to be accommodated is yet to be seen...

**Comment by eugenwintersberger** [comment]
Hi Martin. The reading functions need to be modified for strings thats definitely true. As I have already the code I will have a look on this. If you are satisfied with the strings class just open a pull request. I will have a look on this.

**Comment by eugenwintersberger** [comment]
@martukas  Can we close this for now?
