### ISSUE TITLE
CMake find script for h5cpp_shared should implicitly include HDF5 C library

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#131]

**Comment by eugenwintersberger** [comment]
See #133 . Since CMake version 3.X all dependencies are automatically pulled in by the imported target but we have to provide a fallback for older cmake versions.

**Comment by martukas** [comment]
Ok, so bringing it in as a dependency actually works and this is actually not an issue at all. I'm totally in favor of requiring CMake 3. 
Though I'm still not happy with how the readme explains it :) but I'll handle that myself in #149.
