### ISSUE TITLE
Simplify chunked dataset setup

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#132]
```
property::DatasetCreationList dcpl;
dcpl.layout(property::DatasetLayout::CHUNKED);
dcpl.chunk({100,NBINS});
```

could be a one-liner instead, because
A) if you are setting chunk-size, it is implied that you also want to set the chunked flag
B) such a common case, it practically begs for a dedicated constructor

**Comment by eugenwintersberger** [comment]
I have this on radar. I guess this would be a nice example for constructor based object creation. Having some kind of flat hierarchy of dataset classes. For instance

* `hdf5::node::ChunkedDataset`
* `hdf5::node::VirtualDataset`

Where the constructor is doing the work. I guess we could make this an issue for the 0.0.3 release.
