### ISSUE TITLE
Have ${h5cpp_LIBRARIES} variable available for linking

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#133]
When using find_package for h5cpp with CMake, there is no ${h5cpp_LIBRARIES} variable for linking, and one is forced to manually specify "h5cpp_shared", which is not the idiomatic CMake way of doing it. This variable should also implicitly link ${HDF5_LIBRARIES}

**Comment by eugenwintersberger** [comment]
Actually it is the new way of using CMake (since 3.X). All dependencies are pulled in by the imported target h5cpp_shared. But I guess for old CMake versions we should also provided a ${h5cpp_LIBRARIES} variable.

**Comment by martukas** [comment]
Ok, so bringing it in as a dependency actually works and this is actually not an issue at all. I'm totally in favor of requiring CMake 3. 
Though I'm still not happy with how the readme explains it :) but I'll handle that myself in #149.
