### ISSUE TITLE
Improve node functions

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#134]
Continuation of #36 
* there are probably redundant error checks here
* Parameters could be simplified in light of how our wrapper is designed
* should consider using member functions, as valid node is required for all of them anyways

**Comment by eugenwintersberger** [comment]
Could you be a bit more explicit here? Which methods do you propose?

**Comment by martukas** [comment]
For link creation functions, it would be most intuitive to do
```cpp
base_group.create_link("where/the/new/link/goes", target, lcpl, lapl);
base_group.create_external_link("where/the/other/new/link/goes", target_file, target_path, lcpl, lapl);
```
This is better, because by creating a link you are modifying the base_group, the same object via which you would access it's links. With free-floating functions, it is less obvious. Does the target come before the link location? Is it the other way around? Instead of having to go read docs, it should be intuitive.

Similarly, for removing
```cpp
base_group.remove("path/of/node/to/be/removed", lapl);
```

For move and copy, it is less obvious, but it could be
```cpp
base_group.copy_here("some/new/path", other_node, ocpl, lcpl);
base_group.move_here("other/new/path", other_node, lcpl, lapl);
```

**Comment by martukas** [comment]
@eugenwintersberger any thoughts on this? Would it be ok to implement these?

**Comment by eugenwintersberger** [comment]
After some meditation ... and despite the fact that I still do not like the idea to implement this as member functions. 

For the link functions I suggest the following signatures 

```cpp
void Group::create_link(const hdf5::Path &link_path,
                        const hdf5::Path &target_path,
                        const hdf5::property::LinkCreationList &lcpl,
                        const hdf5::property::LinkAccessList &lapl);
void Group::create_external_link(const hdf5::Path &link_path,
                                 const boost::filesystem::path &target_file,
                                 const hdf5::Path &target_path,
                                 const hdf5::property::LinkCreationList &lcpl,
                                 const hdf5::property::LinkAccessList &lapl);
```
where `link_path` is either relative to the base group or an absolute path.

Remove, copy and move looks good for me. Go ahead.
