### ISSUE TITLE
CMake targets for check_install and uninstall

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#137]
It is probably reasonable to have something like ``make check_install`` to confirm that installation was successful.
Although this may be controversial, ``make uninstall`` or ``make remove`` might also a good idea. The reason I have these concerns is these observations:
* the cmake findpackage file does not appear to be replaced with the newer version when doing make install. Output for other projects invoking it to find h5cpp seems to reflect this situation. It would be good to have some reproducable tests to confirm this.
* If h5cpp is installed on the system then, when compiling, the project may revert to using the installed headers. This has happened on my system. Compiling on Jenkins revealed the problem, but it may be reasonable to be able to uninstall.

**Comment by martukas** [comment]
Implemented the ``uninstall`` taget as per CMake's own [FAQ](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F)
This should solve some problems. I can see that the cmake findpackage seems to be installing and uninstalling correctly, so perhaps one of my above observations as not totally accurate or it was something else. In any case, we are in a better position with this feature in place.
I can't seem to find anything on how to do the equivalent of ``make checkinstall``. Perhaps this is unnecessary?

**Comment by eugenwintersberger** [comment]
`check_install` is definitely an interesting target and also mentioned in the GNU standard if I recall correctly. However, I do not see a purpose for `uninstall`. I do know only very few packages which provide `uninstall` and in virtually all cases it does not work correctly.
