### ISSUE TITLE
Additional group access/creation functions

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#146]
In HDF5, a Group is so ubiquitous an object, that it very likely makes sense to have a few more convenience functions for manipulating them. I propose these two:

* ``Group require_group(...)``
"Open a group in the file, creating it if it doesn’t exist. Exception is thrown if a conflicting object already exists. Parameters as in create_group(...)" taken almost verbating from _h5py_.

* ``bool has_group(name)``
This would be a wrapper for ``g.exists(name) && g[name].type() == Type::GROUP``.

Some analogous functions could exist for Dataset as well.

**Comment by martukas** [comment]
Similarly it should be possible to access a group like this
``auto g = group.group("name")``
rather than
``auto g = hdf5::node::Group(group["name"])```

**Comment by eugenwintersberger** [comment]
I am not sure if I understand `require_group(...)` and what it should do. I definitely agree with you on `has_group` and would add an `is_group` just for convenience. 

Concerning group access: why don't you use 
```cpp
Group g = parent.nodes["groupname"];
```

**Comment by martukas** [comment]
Well,
``Group g = parent.nodes["groupname"];``
works if you want to keep g around for some reason. But if you want to immediately operate on Group "groupname" upon retrieving it, for example:
``parent.nodes["groupname"].create_dataset(...)``
or 
``for (auto members : parent.nodes["groupname"].nodes)``
this is not possible without then also encasing it in a Group constructor. I'm lazy. 99% of the time, you are dealing with groups or datasets, so I think it should be possible to ask it "give me group A" or "give me dataset B", rather than have to think "give me node A, and by the way, it's supposed to be a group". Most of the users will not care to think about this inheritance, or at least will not want to explicitly talk about it every time they retrieve a group member.

**Comment by eugenwintersberger** [comment]
Well, and than again C++ is a statically typed language which would mean that thinking about types is a crucial part of working in C++. What we could do is provide a convenience function that returns all the groups or datasets from a group and store it into a std::map (for instance). 

Another option might be to provide a filter predicate to the NodeView interface that allows iteration only over nodes that satisfy a particular criteria.

**Comment by eugenwintersberger** [comment]
This will also close #22
