### ISSUE TITLE
Additional attribute access/creation functions

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#147]
For writing, given an ``std::string value``, compare:
```
  group.attributes.create<std::string>("some_val").write(value);
```
vs.
```
  group.write_attribute("some_val", value);
```
The amount of type inference is the same, just less boilerplate to repeat. In fact, the second version is safer, in that there is no possible mismatch between attribute type and value type. Additional parameters could also be available, such as property lists.

For reading, compare:
```
  std::string value;
  group.attributes["value"].read(value);
```
vs.
```
  auto value = group.read_attribute<std::string>("value");
```
Here, in a way, the first one might seem more elegant, but only if you have already initialized a variable to which you want to read. That's very thoughtful of someone, very responsible, but also very C-like and is not how Captain Kirk flies. A one-liner should be possible :)

**Comment by martukas** [comment]
In addition to this, I wonder if there is a more laconic way of doing
``attribute.datatype() == datatype::create<int32_t>()``
Perhaps something along the lines of
``bool happy = attribute.is<int32_t>()``
which, if we consider that there is an HDF5 mechanism for type conversion, might be a hint at how we could check whether it is possible to convert, i.e.
``bool not_sad = attribute.can_convert<int32_t>()``

**Comment by eugenwintersberger** [comment]
First of all: this is C++ not Java ;) I do not recommend using something like read_attribute(), write_attribute() for at least two reasons

1. they scatter responsibilities over classes which should be handled by only one class (Attribute is responsible for doing the IO thing and nothing else)
2. your interfaces grow for no reason (this is what I love on C++ libraries and what I hate on Java libraries - I am actually diving into Java for a side kick project, so I know what I am talking about)

Concerning the read interfaces: if you mean something like this 
```cpp
auto value = root.attributes["HDF5_version"].read<std::string>();
```
I am thinking about having something like this. But it requires a bit more work on the side of the type traits. I would like to do this when I review the IO code. One would need some extra trait describing how to produce a particular type (we also want to have this for user defined types, right?). 

I am a little bit confused what this here should mean
```cpp
bool happy = attribute.is<int32_t>();
```
and
```cpp
bool not_sad = attribute.can_convert<int32_t>();
```
So the basic idea is that you know the type you want to read from a dataset or attribute and the library will do a conversion of needed. So the first line above, if I understood it correctly, would read like this 
```cpp
auto happy = attribute.read<bool>();
```
But maybe we should talk about this in a hangout ;)

**Comment by martukas** [comment]
So,
```cpp
auto value = root.attributes["HDF5_version"].read<std::string>();
```
looks alright. There is no redundant or superfluous information. What's your suggestion for an analogous write function? You should not have to explicitly specify the value to be written already has a type that the compiler can see.

Happy was the yes/no answer to the question of whether the attribute _is_ of a specific type, in this case of int32. Compare with the first line of code in that comment. I suppose we could have some predefined types? Do we have wrappers for them? But it's nice if you can answer the question of "is this an int32_t"? Rather than "is this SOME_H5_SPECIFIC_CONSTANT_FOR_INT32_THAT_I_HAVE_TO_LOOK_UP?" No, it's not to "cast" it, but rather to answer

**Comment by eugenwintersberger** [comment]
For writing we could do something like this 

```cpp
root.attributes.create("name",value)
```
Actually we could reuse the machinery we already have in place (though it needs some review) to deduce the datatype and dataspace from `value`. 

Ah, now I understand what you mean. So some kind of introspection. Actually if you want to do this for a particular dataset or datatype you could do something like this

```cpp
if(attribute.datatype() == datatype::create<int32_t>())
{
}
```
or wrap this into a predicate function 

```cpp
template<typename T,typename IOType>
bool is_of_type(const IOType &object)
{
   static_assert(std::is_same<IOType,Dataset>::value || std::is_same<IOType,Attribute>::value);

   return object.datatype() == datatype::create<T>();
}
```

Checking whether type are convertible is I but more effort. But I would first have a look whether or not there is some HDF5 API function available for this check.
