### ISSUE TITLE
Build fails on Windows 7 with visual studio 2015

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#174]
Get the following error message

```
 D:\Development\h5cpp\src\h5cpp\error\error.cpp(59): error C3861: 'open_memstream': identifier not found
```

In addition there are a log of warnings concerning missing DLL interfaces.

**Comment by eugenwintersberger** [comment]
`open_memstream` is only available on Linux (maybe the other Unix systems too). We need a replacement for this.

**Comment by martukas** [comment]
Yes, we are aware of this. Merging #84 should resolve this issue.
