### ISSUE TITLE
Provide Conan packages for h5cpp on ess-dmsc

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#186]

**Comment by eugenwintersberger** [comment]
Take care about conan. They moved to version 1.0.0 - a lot of things have changed. Currently fixing my own packages ;)

**Comment by martukas** [comment]
Conan packages are now successfully generated by:
https://github.com/ess-dmsc/conan-h5cpp
For now, the package can be included in another project as:
h5cpp/packaging-test@ess-dmsc/testing
Once we release v0.0.4, we will update the job to reflect that.
