### ISSUE TITLE
Node objects should get an explicit close() method

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#197]
In some situations it is necessary to explicitely destroy on object. Currently we cannot do this.

**Comment by martukas** [comment]
The current go-to way to close any HDF5 object goes like this:
``ObjectHandle(static_cast<hid_t>(lapl)).close();``
It is somewhat awkward, I admit, but in reality we only need to do this explicit closing in rather hacky cases, i.e. in unit tests where we seek to provoke an exception.
Given our drive towards RAII patterns with this wrapper, I have to ask what is the motivation for having an explicit close method for nodes?
