### ISSUE TITLE
Reverse iterator for links and nodes

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#200]
It could be that this is already doable via IteratorConfig, but for STL idioms, we might want to have `rbegin()` and `rend()` available. Furthermore, we have prefix and postfix increment and decrement operators for these iterators, but these are not covered by the tests. Some completeness here would be nice.

**Comment by eugenwintersberger** [comment]
I was thinking about reverse iterators but they do not make sense as HDF5 has no unique ordering of the nodes in a tree unless you specify it with the IteratorConfig object. So reverse iteration does not make sense at all. 

I do though agree with your request for more coverage in the iterator tests. ;)

**Comment by eugenwintersberger** [comment]
Does not make sense in the context of HDF5 object iteration. So we can close this.
