### ISSUE TITLE
Review code for LinkTarget

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#201]
`LinkTarget` (and parts of it that work with `Link`) seem to be lacking test coverage. This makes me think that there was something clever in mind when designing it, but the awesomeness was not actually used in the end. The documentation should be more clear on the motivation for this class and how exactly it relates to `Link`.

**Comment by eugenwintersberger** [comment]
The ``Link`` class itself could not provide information about the target of a link without touching it. This becomes problematic in particular in the case of an external link if the file does not exist. In this case the ``LinkTarget`` class provides all the information required to resolve the situation (in this case the path to the file where the node the external link refers to is stored).

**Comment by eugenwintersberger** [comment]
I see your point. The problem is rather simple: when

**Comment by eugenwintersberger** [comment]
Sorry, just accidentally closed the issue.
