### ISSUE TITLE
segfault in property_class

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/h5cpp#219]
I get a segfault at https://github.com/ess-dmsc/h5cpp/blob/69517e9e41937207063633af4d0d12d26c40eecc/src/h5cpp/property/property_class.cpp#L49
This occurs when running unit tests at https://github.com/ess-dmsc/h5cpp/blob/69517e9e41937207063633af4d0d12d26c40eecc/test/property/property_class_test.cpp#L36

Using `H5free_memory()` instead of `free()` does not segfault, but does fail to free the memory as tests pass but the following is reported afterwards:
```
unit_tests: ../hdf5-1.10.1/src/H5MM.c:232: H5MM_final_sanity_check: Assertion `0 == H5MM_curr_alloc_bytes_s' failed.
```

_I am using Ubuntu 16.04, gcc 5.4.1, and am using `conanfile_ess.txt` for dependencies._

**Comment by eugenwintersberger** [comment]
After reading through the HDF5 documentation the unfortunate result is that there is not really a good workaround for this. We get a plain pointer and have to deal with it. What makes things a bit more complicated is the fact that we do not see this error on any of the test systems.

**Comment by eugenwintersberger** [comment]
Does this happen with all the tests in this test function or only for kAttributeCreate?

**Comment by martukas** [comment]
I think it was possibly resolved as build environment-related issue? @matthew-d-jones ?

**Comment by matthew-d-jones** [comment]
This is a weird way for it to manifest, but yes, I've just done a clean rebuild and all is now well. Sorry to cause confusion, I will close the issue.

@eugenwintersberger I agree there does not seem to be a nicer solution to dealing with these raw pointers from hdf5. The use of `free()` looked suspicious to me, even though it is correct to use it here, perhaps using `H5free_memory()` would make it a little more obvious that it is the expected method of cleaning up that pointer?
