### ISSUE TITLE
Implicit constructor for Path?

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#22]
Syntax such as copy(gt, g2, Path("gt")) feels superfluous.
Perhaps Path could be constructed from std::string implicitly?
We may keep it this way for now while we are testing and developing, but relax this later. Any arguments for or against?

**Comment by eugenwintersberger** [comment]
Good idea. I am somtimes a bit too strict when it comes to the usage of the explicit keyword ;)
