### ISSUE TITLE
h5cpp_FOUND in CMake

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#222]
Something like `h5cpp_FOUND` should be made available for client CMake projects to facilitate optional features.

**Comment by martukas** [comment]
Related to this, check out this pull request for our file writer:
[Pull in h5cpp as a dependency, supports Conan as well as non-Conan #113](https://github.com/ess-dmsc/kafka-to-nexus/pull/113/files)
Apparently this is something they need to do for Centos6, which, of course, we don't actually support, but perhaps our facilities for `find_package()` need to be more robust?

**Comment by eugenwintersberger** [comment]
Actually h5cpp_FOUND should be set by find_package automatically. At least this is how it works on my systems and how it is described in the documentation.

**Comment by eugenwintersberger** [comment]
I just had a look on the pull request: what CMake version are these guys using?

**Comment by martukas** [comment]
This is actually working fine. Not our fault.
