### ISSUE TITLE
Make it warning-free

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#223]
Overkill, one might say. However, there are people out there that impose such expectations on themselves. They bring in h5cpp as a dependency, with `-Wall -Wpedantic -Werror` on and all hell breaks loose :) Of course, we can sidestep it with pragmas. I think it's achievable in the not-too-distant future.

**Comment by eugenwintersberger** [comment]
Yeah. That would be really cool. I have this on my schedule in particular because it makes it hard to identify real error messages particularly on Windows. Actuall, if I recall correctly we are building with `-Wall -Wpedantic -Werror` too, aren't we?

**Comment by martukas** [comment]
No, it is not -Werror, beacause we would surely fail then :)
