### ISSUE TITLE
NodeView::exists does not work correctly

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#23]
Came across this while developing tests for node copy functions. I will attempt to develop a test suite for NodeView. Hopefully I can track down the problem myself. Else, you may have some insight.

**Comment by martukas** [comment]
So, in fact it works. I just needed to read the H5 documentation to understand that it officially works in a way that does not entirely make sense :)

Cleaning this up has resulted in the following:
1) Path class now was equality comparators. One of them is a friend function to enable direct comparison of member variables rather than some stringified cast. Does this make sense? Not sure how this affects the Windows-specific DLL_EXPORT thing.
2) Path class tests now cover equality operators.
3) Link class now has equality operators and stream output operator.
4) Tests for the Link class are lacking. Created ticket for this.
5) Last, but not the least: Group now has an exists(name, proplist) function which does what an entity from our galaxy would expect it to do, i.e. it first tests if the link exists and then tests if it points to an existing node. Thus the question of existence is answered in a simple way, rather than having to catch an exception and/or return value.
6) As a bonus there are more tests for LinkView, NodeView within the group_test suite.

**Comment by eugenwintersberger** [comment]
That sounds great to me. Can you please merge this and close the ticket so I can use it in my code ;)?
