### ISSUE TITLE
Stream output for more complex types

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#231]
Enums and flags get lexical casting via the stream output functions. Should we make it possible to also do printout of other hdf5 objects (at the very least Datatypes or Dataspaces) for the sake of debug output? Potential benefits:
* More informative exceptions with higher level information on context of failure.
* Facilities for debugging in client programs.
* One step closer to an interactive hdf5 browser

**Comment by eugenwintersberger** [comment]
Stream IO would be interesting for all IO objects. However, we should first do the IO review. As I am working on the Python wrapper I see some issues which are easily resolveable but we need to do this. I hope I can start with this beginning of march.
