### ISSUE TITLE
Divorce boost in favor of just file_system

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#233]

**Comment by eugenwintersberger** [comment]
what exactly is the motivation for this?

**Comment by martukas** [comment]
Boost is big. Even (or especially) with conan, if every time you build h5cpp you need to build all of boost, it gets nasty. Some have suggested bincrafters recipes that make separate boost components available. Just giving this a try. If it turns out better, we will switch to it. Plus, if we don't have to maintain Boost packages & binaries ourselves (at ESS), that would be an advantage.
