### ISSUE TITLE
h5cpp-config.cmake should not be located in the root of the repository

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#243]
Due to the way that CMake searches for packages, the wrong version of `h5cpp-config.cmake` is sometimes used.
E.g. `h5cpp` is located in `~` and `~/bin` is in your `$PATH`.

This is problematic as the `h5cpp-config.cmake` file in the root of the repository is actually a template.
Fixing this is done by either moving `h5cpp-config.cmake` to another directory in the repository or by renaming the file to something that is not picked by the CMake `find_package()` command.

I do not mind fixing this but I would like to know if you have any comments (@martukas @eugenwintersberger ) before creating a pull request.

**Comment by eugenwintersberger** [comment]
I never had this issue but if you can fix it go ahead :)
