### ISSUE TITLE
Missing compile time error

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/h5cpp#258]
I can not see how these statements in the comments can be true.

`hid_t` is trivially copyable. Move semantics should not matter here. As far as I can see it is indeed possible (and the default) that this constructor, given an lvalue `hid_t`, assumes shared ownership without incrementing the reference count.

https://github.com/ess-dmsc/h5cpp/blob/fcbb2f2c29ef1d2fc347c1f80ba2cc367e5bb41c/src/h5cpp/core/object_handle.hpp#L133-L146

**Comment by eugenwintersberger** [comment]
This statement is definitely not true. It seems that some ancient fragments have remained. Need to fix this.

**Comment by martukas** [comment]
Taken care of in code review #262
