### ISSUE TITLE
Warnings in dataset_creation_list.cpp

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#26]
Quite a few along the lines of:

``
/home/bdv/dev/h5cpp/src/property/dataset_creation_list.cpp: In function ‘std::ostream& hdf5::property::operator<<(std::ostream&, const hdf5::property::DatasetFillValueStatus&)’:
/home/bdv/dev/h5cpp/src/property/dataset_creation_list.cpp:44:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
``

This is after after switch statements for stream output of enums. Should _theoretically_ never happen, but who knows. What's the right way to deal with this? Return stream unaltered or insert some sort of FU? :)

**Comment by martukas** [comment]
Similar case in selection_manager.cpp

**Comment by eugenwintersberger** [comment]
Yeah. This is a bit annoying with gcc. I guess the best solution is a pragma to fix theses kinds of warnings. There are special pragmas to switch of compiler warnings for marked sections of code.
