### ISSUE TITLE
Bool IO fails on Debian 8

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#260]
This is somehow a strange regression as it has already worked. More investigation required.

**Comment by eugenwintersberger** [comment]
I did some research: Debian 8 uses version 1.8.13 of the HDF5 library. There seems to be a difference how boolean data is stored in HDF5 between 1.8.13 and 1.10.1. 

Writting a test file and comparing the output of `h5ls` I get for 1.8.13

```
/                        Group
    Attribute: bool_attr scalar
        Type:      native int
        Data:  1083224065
    Location:  1:96
    Links:     1
/bool_dataset            Dataset {SCALAR}
    Location:  1:888
    Links:     1
    Storage:   4 logical bytes, 4 allocated bytes, 100.00% utilization
    Type:      native int
    Data:
        (0) 1083224065

```

and for 1.10.1

```
/                        Group
    Attribute: bool_attr scalar
        Type:      native unsigned char
        Data:  1
    Location:  1:96
    Links:     1
/bool_dataset            Dataset {SCALAR}
    Location:  1:888
    Links:     1
    Storage:   1 logical byte, 1 allocated byte, 100.00% utilization
    Type:      native unsigned char
    Data:
        (0) 1
```
Not only is the data stored correctly in the latter case, there is also a different integer type used for 1.10.1.

**Comment by martukas** [comment]
@eugenwintersberger is this to be solved soon, or can we postone this out of the 0.0.7 release?

**Comment by eugenwintersberger** [comment]
I guess we cannot easily solve this problem without introducing our own boolean type. The reason for this bug is, at least in my opinion, an error in the HDF5 C-API concerning the handling of the boolean data type. So I suggest to close this ticket by marking it as *won't be fixed*.

**Comment by jkotan** [comment]
I've just added tests for reading bool attributes created by `h5py` and `pniio`. Files created with HDF5_version 1.8.13 and 1.10.0 looks the same so I put only one version. `h5py` creates attributes as

    Attribute: bool_array {4}
        Type:      enum native signed char {
                   FALSE            = 0
                   TRUE             = 1
               }
        Data:  FALSE, TRUE, TRUE, FALSE
    Attribute: bool_scalar_false scalar
        Type:      enum native signed char {
                   FALSE            = 0
                   TRUE             = 1
               }
        Data:  FALSE

while old `pniio` as

    Attribute: bool_array {4}
        Type:      8-bit unsigned integer
               (1 bit of precision beginning at bit 0)
               (7 zero bits at bit 1)
        Data:  0, 1, 1, 0
    Attribute: bool_false {1}
        Type:      8-bit unsigned integer
               (1 bit of precision beginning at bit 0)
               (7 zero bits at bit 1)
        Data:  0

My tests are in the https://github.com/ess-dmsc/h5cpp/tree/issue_260 and it looks like that bool attribute data is readable for enum `scalar` and integer size-1 `simple` as `bool` or `unsigned char`. 
To read `bool_array` I can use only `std::vector<unsigned char>` buffer. When I try to use `std::vector <bool>` buffer by example uncommenting https://github.com/ess-dmsc/h5cpp/blob/d89a4c8aa46e6d1b5587f463f738915663e9fbd0/test/attribute/attribute_h5py_bool_test.cpp#L78

 I get compilation error (for `h5py` and `pniio` as well)

    [ 39%] Building CXX object test/CMakeFiles/unit_tests.dir/attribute/attribute_h5py_bool_test.cpp.o
    In file included from /home/jkotan/sources/h5cpp/src/h5cpp/attribute/attribute.hpp:30:0,
		     from /home/jkotan/sources/h5cpp/src/h5cpp/attribute/attribute_iterator.hpp:29,
		     from /home/jkotan/sources/h5cpp/src/h5cpp/hdf5.hpp:38,
		     from /home/jkotan/sources/h5cpp/test/attribute/attribute_h5py_bool_test.cpp:26:
    /home/jkotan/sources/h5cpp/src/h5cpp/dataspace/type_trait.hpp: In instantiation of ‘static void* hdf5::dataspace::TypeTrait<std::vector<T> >::ptr(std::vector<T>&) [with T = bool]’:
    /home/jkotan/sources/h5cpp/src/h5cpp/dataspace/type_trait.hpp:121:27:   required from ‘void* hdf5::dataspace::ptr(T&) [with T = std::vector<bool>]’
    /home/jkotan/sources/h5cpp/src/h5cpp/attribute/attribute.hpp:307:33:   required from ‘void hdf5::attribute::Attribute::read_contiguous_data(T&, const hdf5::datatype::Datatype&) const [with T = std::vector<bool>]’
    /home/jkotan/sources/h5cpp/src/h5cpp/attribute/attribute.hpp:384:5:   required from ‘void hdf5::attribute::Attribute::read(T&, const hdf5::datatype::Datatype&) const [with T = std::vector<bool>]’
    /home/jkotan/sources/h5cpp/src/h5cpp/attribute/attribute.hpp:359:3:   required from ‘void hdf5::attribute::Attribute::read(T&) const [with T = std::vector<bool>]’
    /home/jkotan/sources/h5cpp/test/attribute/attribute_h5py_bool_test.cpp:78:16:   required from here
    /home/jkotan/sources/h5cpp/src/h5cpp/dataspace/type_trait.hpp:77:12: error: void value not ignored as it ought to be
	 return reinterpret_cast<void *>(data.data());
		^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    test/CMakeFiles/unit_tests.dir/build.make:1766: recipe for target 'test/CMakeFiles/unit_tests.dir/attribute/attribute_h5py_bool_test.cpp.o' failed
    make[3]: *** [test/CMakeFiles/unit_tests.dir/attribute/attribute_h5py_bool_test.cpp.o] Error 1
    CMakeFiles/Makefile2:683: recipe for target 'test/CMakeFiles/unit_tests.dir/all' failed
    make[2]: *** [test/CMakeFiles/unit_tests.dir/all] Error 2
    CMakeFiles/Makefile2:722: recipe for target 'test/CMakeFiles/run_tests.dir/rule' failed
    make[1]: *** [test/CMakeFiles/run_tests.dir/rule] Error 2
    Makefile:242: recipe for target 'run_tests' failed
    make: *** [run_tests] Error 2

It looks like implementation of `Trait` for std::vector<bool> is missing.

**Comment by jkotan** [comment]
I've added tests for reading boolean datasets. They behave similarly to attributes (with the compiler error above).

**Comment by jkotan** [comment]
I've reproduced the problem @eugenwintersberger mentioned at the beginning. I agree with Eugen that in order to fix the problem we should rewrite the code for bool type by introducing our own type. Especially H5T_NATIVE_HBOOL causes other problems like #354, i.e. you cannot distinguish it from `int` type, so writing `bool` variables we loose the information about their type. So it is not real `bool` type but `int`.

**Comment by jkotan** [comment]
BTW, since the enum type are already implement the `bool` type could be a good use case for them.

**Comment by jkotan** [comment]
I've just added the test to read hdf5 1.8.13 and 1.10.0 data at https://github.com/ess-dmsc/h5cpp/blob/issue_260/test/attribute/attribute_h5cpp_bool_test.cpp but it looks like the bool attributes are readable (except multi-dimentional which are not supported because of std::vector<bool> problem).

@eugenwintersberger could you please provide a test which reproduces the problem you have noticed?

**Comment by jkotan** [comment]
From my test it looks like that the original problem exists only in python binding of `h5cpp`, i.e. python-pni. It is related to mapping python `bool` types to c++ integer types.

**Comment by jkotan** [comment]
For python https://github.com/pni-libraries/python-pni/pull/67 fixes the issue.

@eugenwintersberger, if this error also exists for c++? If so could you provide tests.

**Comment by eugenwintersberger** [comment]
I guess I put this on the list of issues we should discuss tomorrow ;)

**Comment by eugenwintersberger** [comment]
After discussing this with Jan again. We can close this.
