### ISSUE TITLE
ESS code review

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#262]
The software team at ESS is doing code review of each of our significant projects. We will do this for h5cpp as well. It can benefit from having some additional eyes on it. @mattclarke will lead this review on Wednesday, March 21.

**Comment by eugenwintersberger** [comment]
Sounds like a great idea to me. I am already curious about the results.

**Comment by martukas** [comment]
Code review resulted in tickets #270 and #271, but there may be more things to look at in there. I will take on the task of reviewing the code review :)

**Comment by martukas** [comment]
We have implemented all of the recommendations, save a few that are either already covered by tickets or have received new ones as separate issues.
