### ISSUE TITLE
Writing C-style arrays

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#273]
I am having trouble figuring out how to write C-style arrays (e.g. `double Data[6]`) to a dataset without copying it to a `std::vector` first. I have yet to find an example in either the _example_ directory or the unit tests. If you can give me some sample code I will create an example from it.

**Comment by eugenwintersberger** [comment]
I van have a look in this tomorrow oe in monday

**Comment by SkyToGround** [comment]
As a temporary solution, I am using `gsl::span` ([see here](https://github.com/Microsoft/GSL)) and the following code:
```c++
template<>
class TypeTrait<unsigned short const> {
public:
  using Type = unsigned short const;
  using TypeClass = Integer;
  static TypeClass create(const Type & = Type()) {
    return TypeClass(ObjectHandle(H5Tcopy(H5T_NATIVE_USHORT)));
  }
};

template<typename T>
class TypeTrait<gsl::span<T>> {
public:
  using Type = gsl::span<T>;
  using TypeClass = typename TypeTrait<T>::TypeClass;
  static TypeClass create(const Type & = Type()) {
    return TypeTrait<T>::create();
  }
};
```

This is not a permanent solution as `gsl::span` is an extra dependency and it requires C++14. However, a similar solution might be appropriate if it is provided by h5cpp directly.

**Comment by SkyToGround** [comment]
Turns out that I was wrong, the above mentioned temporary solution did not work as expected. For some reason I get the following error message when using it:
```
[ RUN      ] FastSampleEnvironmentWriter.WriteDataOnce
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: ../hdf5-1.10.1/src/H5Dio.c line 269 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: ../hdf5-1.10.1/src/H5Dio.c line 345 in H5D__pre_write(): can't write data
    major: Dataset
    minor: Write failed
  #002: ../hdf5-1.10.1/src/H5Dio.c line 692 in H5D__write(): src and dest data spaces have different sizes
    major: Invalid arguments to routine
    minor: Bad value
unknown file: Failure
C++ exception with description "Failure to write contiguous data to dataset [/SomeParentName/raw_value]!" thrown in the test body.
[  FAILED  ] FastSampleEnvironmentWriter.WriteDataOnce (225407 ms)
```
Do you have any ideas (@martukas @eugenwintersberger )?

**Comment by eugenwintersberger** [comment]
Another possibility would be to provide something like an adapter class. This could be done easily 

```cpp
template<typename T> class ArrayAdapter
{
  private:
    T *data_;
   size_t size_;
 public:
   ArrayAdapter(T *data,size_t size);

size_t size() const;
 T *data();
 const  T *data() const;
};
```
With this you can latter use the common mechanisms to write data. I would rather prefer this approach over creating new template functions for IO. We maybe could add this adapter to the library.

**Comment by SkyToGround** [comment]
Using an adapter would seem to be the cleaner solution in my opinion. Are the member functions `size()`, `data()` and `const data()` the only ones required by h5cpp?

**Comment by SkyToGround** [comment]
Oh, and one more thing `const` versions of the primitive versions of `hdf5::datatype::TypeTrait` should also be a part of the h5cpp library. For example:
```c++
hdf5::datatype::TypeTrait<const int>
```

**Comment by martukas** [comment]
This has been branched off into separate tickets & we know the functionality actually works with correct usage of traits. I consider this ticket closed.
