### ISSUE TITLE
Better compiler warning for missing Dataspace traits

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#276]
Split off of #273

Compiler should provide some useful warnings if `hdf5::dataspace::TypeTrait<>` is missing or is not used correctly.

This is not an error in the implementation per se, but if we intend the library to be easily usable for custom user-defined types, it would be desirable that the compiler provide some useful information if the architecture is not being used correctly.

**Comment by eugenwintersberger** [comment]
This needs some investigation but this is most probably difficult to do.

**Comment by zjttoefs** [comment]
May be doable in C++20.
