### ISSUE TITLE
Const type traits

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#277]
There should be `const` versions of the primitive versions of `hdf5::datatype::TypeTrait`. For example:
```c++
hdf5::datatype::TypeTrait<const int>
```
Split off of #273

**Comment by martukas** [comment]
@SkyToGround could you please provide us with an example where lack of this feature creates a problem? A test case, if you will?

**Comment by eugenwintersberger** [comment]
Better go for [this](https://en.cppreference.com/w/cpp/types/remove_cv) in our code.

**Comment by SkyToGround** [comment]
@martukas sure, take a look at line 119 in this file: https://github.com/ess-dmsc/kafka-to-nexus/blob/master/src/schemas/senv/FastSampleEnvironmentWriter.cpp

The pointers I get to the flatbuffer vectors are `const`  pointers.

**Comment by SkyToGround** [comment]
I guess that a good simple test case would be to write the following data to a dataset:
```
const std::int32_t TestArr[] = {0,1,2,3};
```

**Comment by eugenwintersberger** [comment]
I think we can avoid an extra trait but rather use template functions like `std::remove_const`.

**Comment by SkyToGround** [comment]
This appears to be a problem again in the latest version of h5cpp (i.e. 0.1.3). I have not investigated it in detail yet though.

**Comment by eugenwintersberger** [comment]
Can you please post an example when the error occurs?

**Comment by SkyToGround** [comment]
Example: https://github.com/ess-dmsc/kafka-to-nexus/pull/431
Note however, that the "unit test" that is supposed to guard against this regression is still in the code base (without failing to link) so I am not sure what is happening here.

**Comment by SkyToGround** [comment]
The attached file shows the failing behaviour. It should probably be added as a unit test.

[write_c-array.cpp.zip](https://github.com/ess-dmsc/h5cpp/files/3181870/write_c-array.cpp.zip)

**Comment by eugenwintersberger** [comment]
Ok. The problem here is the trait for the data type. In order to fix this problem you have to modify it in the following way

```cpp
namespace hdf5 {
namespace datatype {

template <typename T> class TypeTrait<ArrayAdapter<T>> {
public:
  using Type = ArrayAdapter<T>;
  using TypeClass = typename TypeTrait<T>::TypeClass;
  static TypeClass create(const Type & = Type()) {
    return TypeTrait<typename std::remove_const<T>::type>::create();
  }
};
}}
```

The trick here is to use the `std::remove_const<T>`. There is now way how to deal with this automatically (at least I do not have one in mind). However, it is in general a good idea when working with templates to remove cv-qualifiers if not necessary.
I will close this issue for now
