### ISSUE TITLE
Intuitive way to get node's relative path?

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#28]
Right now, if you want to get the Node's parent, you can do this:
source.link().parent(), which give you a Group object, which is not bad

If you want it's path relative to the parent, you have to do this:
Path(object.link().path().back()) which is a bit crazy

Maybe there should be some more convenient functions for this? Or maybe we only need these internally and the user will never need them?

What comes to mind as a good example is something like boost::filesystem::path::stem() which gives you just the filename without the rest of the path. But maybe there is some deeper question here, or need of some general functions to resolve relative paths?

**Comment by eugenwintersberger** [comment]
I would rather go with path releated functions. Something like 

~~~{cpp}
Path hdf5::Path::name(const Path &p) //return relative path
Path hdf5::Path::parent(const Path &p) //return parent path
~~~

**Comment by martukas** [comment]
However, if these functions operate on const-ref parameters, why not have them as member methods?

~~~{cpp}
Path hdf5::Path::name() const //return the stem
Path hdf5::Path::parent() const //return parent path
Path hdf5::Path::relative_to(const Path &other) const //return path of object relative to other
~~~

This seems to me more intuitive. Of course, then there is the edge case of root path, but we deal with that anyway.
This reminds me of another thing that came to me: some characters are forbidden in h5 paths, such as ".". Do we pass the buck to H5 or do any checking of user supplied strings?

**Comment by martukas** [comment]
It seems that whitespace and punctuation are perfectly valid for group names. I vaguely remember some issues with attribute naming, but we can catch that on later tests. Group names can even be mutiple whitespace with no alphanumerics, or even "..", only the one dot "." being reserved to identify current path.
is_valid_child_name will likely be removed, and for node names we will use Path with the additional requirement that it be size=1. This can later be relaxed as some functionality is developed to deal with intermediate path construction "on the way" to the final node.

**Comment by eugenwintersberger** [comment]
Looks all good to me. When it comes to member function vs. free standing function than I usually I try to implement functionality where I do not need to access the internals of a class as functions and otherwise as members. In this case we do not need to access the class internals. But I have to admit that I sometimes do not follow my own rules as strictly ;)

**Comment by eugenwintersberger** [comment]
Concerning "." and "..". I usually use them as on  a file system in access functions of coarse you have to resolve them before you can path the final path to HDF5.

**Comment by martukas** [comment]
More changes to Path:
1) Function common_base for finding the longest common base for two paths
2) Function relative_to for defining one path relative to another (must have common base)
3) Paths relative to child (as with ".." in shell) are not allowed, as per previous discussions
4) All strings parsed as Path are sanitized of empty tokens, "." or repeated "/"
5) Access to path tokens via front() and back() is no longer available, nor is inserting via push_front/back, as this would essentially require parsing and sanitation. The Proper way to append to Path is via arithmetic operators, for example, the newly added +=. I have trouble thinking up of reasons to push_front, but that is also essentially possible by doing string + Path; In all these cases, the path is converted to Path, in the process of which it is also sanitized
6) For a similar reason, non-constant iterators are also not available. The client should not be able to insert arbitrary tokens into Path.
7) There's a question of whether const iterators should are needed either. The only place they are used is sequentially access each level of a path in Group Link::parent() const. Since, as far as I know, HDF is capable of opening absolute paths, perhaps this should be done via H5Gopen without iteration? This could be a separate ticket.
8) name() and parent() methods are now part of Path
