### ISSUE TITLE
Direct Chunk Write ( H5DOwrite_chunk)

### ISSUE THREAD

**Issue by yuelongyu** [ess-dmsc/h5cpp#286]
Dear all,

I want to write precompressed data to Nexus file, meaning bypassing the filter chain. Before I was using pniio1.1.0 to create file and H5DOwrite_chunk, it worked well on Debian 8. However, according to my current tests, this doesn't work anymore on Debian 9. Now I am moving to pniio1.2.0 + h5cpp, I want to ask if this is already implemented in h5cpp because I cannot really find similar thing in the h5cpp APIs. If not, will this be supported later?

**Comment by eugenwintersberger** [comment]
Hi yuelong. Writing precompressed data to an HDF5 file is a rather esoteric feature and I guess it will take a while (if at all) until we add support for this to h5cpp. The major difference between Debian 8 and 9 is that the former still uses HDF5 1.8 while Debian 9 is already on HDF5 1.10. So I would first suspect that the issue can be found there. More interestingly, can you post a code snipped showing how you are writing the data?

**Comment by yuelongyu** [comment]
Just post the comment here too.
Here are the part for writing compressed data. The dataset filed ID is fetched via PNIIO.
/**
* @brief get field id
* @param field
* @return field id if successful; Otherwise it returns a negative value
*/
template
int GetFieldID(const T &field)
{
nxgroup g = field.parent();

        return H5Dopen(g.imp().object().id(),
                       field.name().c_str(),
                       H5P_DEFAULT);
    }

/**
* @brief write 2D data
* @param data
* @param length of the data
* @param nx
* @param ny
* @param frame number field name
* @param error code field name
* @param frame number
* @param error code of the frame
* @return error code.
* 0: OK;
*/
int Write2DCompressedData(string strDataFieldPath,vector& vuchData,int nDataLength
,int nX, int nY
,string strFrameFieldPath,long lFrameNo
,string strErrCodeFieldPath,short shErrCode)
{
int nRet = 0;

        if((nRet = Write1DData<long>(lFrameNo,strFrameFieldPath)) != 0)
            return nRet;

        
        if((nRet = Write1DData<short>(shErrCode,strErrCodeFieldPath)) != 0)
            return nRet;

   
        //select field
        if((nRet = SelectField(strDataFieldPath)) != 0)
            return nRet;

    
        //get dataset field id
        int nID = GetFieldID(m_nxField);
        if(nID < 0)
            return GET_FIELD_ERROR;
    
        try
        {

            int nSize = GetWritePositionFor2DData(nX*nY);

            if(nSize == -1)
                return INDEX_ERROR;

            long long unsigned int nOffset[3] = {static_cast<long long unsigned int>(nSize),
                                                 0,
                                                 0};
            //do chunk write
            int nRet = 0;

            nRet = H5DOwrite_chunk(nID //dataset id
                                   ,H5P_DEFAULT //not used
                                   ,0 //filter mask. 0 means with filter
                                   ,&nOffset[0] //logic position of the chunk's first element in dataspace
                                   ,nDataLength //data size
                                   ,reinterpret_cast<unsigned char*>(&vuchData[0]) // data
                                   );
	
            if(nRet < 0)
                return WRITE_ERROR;
            
            m_nxFile.flush();

            H5Dclose(nID);
            
            return NO_ERROR;
        }
        catch(invalid_object_error& ie)
        {
            DisplayError(__FUNCTION__,"",INVALID_OBJECT_ERROR);
            return INVALID_OBJECT_ERROR;
        }
        catch(object_error& oe)
        {
            DisplayError(__FUNCTION__,"",OBJECT_ERROR);
            return OBJECT_ERROR;
        }
        catch(type_error& te)
        {
            DisplayError(__FUNCTION__,"",TYPE_ERROR);
            return TYPE_ERROR;
        }
        catch(size_mismatch_error& se)
        {
            DisplayError(__FUNCTION__,"",SIZE_MISMATCH_ERROR);
            return SIZE_MISMATCH_ERROR;
        }
        catch(io_error& ie)
        {
            DisplayError(__FUNCTION__,"",IO_ERROR);
            return IO_ERROR;
        }
    }

When writing compressed data on Debian 9. The following warning/error appears.
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139924163015232:
#000: ../../../src/H5Dio.c line 225 in H5Dwrite(): not a dataset
major: Invalid arguments to routine
minor: Inappropriate type

I just put the project into stash repo in DESY. The whole project can be fetched from stash now.
https://stash.desy.de/scm/yy/filewriter.git

**Comment by martukas** [comment]
You could also use h5cpp to manage all resources - group, dataset creation, etc.. and then just use the C API for the direct chunk writing only. You can always access the underlying `hid` of every object managed by h5cpp by using `static_cast<hid_t>(some_object)`. That is a temporary solution, of course, but it would allow you to take advantage of the wrapper to avoid other cumbersome C code.

**Comment by yuelongyu** [comment]
Hi Martin. Thanks a lot. That's what I am looking for. I've tried it and this works for me.

**Comment by martukas** [comment]
Further note: if you do use a C API function, then you will need to do your own checking for returned error values. If it does turn out to be an error, you can extract the HDF5 error stack and throw an exception with that wrapped in there. Look through our implementation code for lines that go `throw_with_stack` or `throw_with_nested` for examples. My recommendation is that you run your program with `hdf5::error::Singleton::instance().auto_print(false);` early on in your `main.cpp` to make sure that the error info ends up in exceptions rather than polluting your standard output. If you get your code into a working state, it could come close to an implementation we could then add to the library.
Sorry, we are still polishing other parts of this and have a pretty long backlog of issues generated by our primary projects.

**Comment by yuelongyu** [comment]
Thanks for your suggestion, I'll take a look.

**Comment by jkotan** [comment]
It is duplicated with #19
