### ISSUE TITLE
pkgconfig files

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#302]
Hi,

In tango framework Makefiles are generated automatically from pogo.  Therefore in Tango servers it is not convenient to use cmake. It would be really helpful to add pkgconfig files to simplify linking process. Currently, all link parameters we have to put by hand, i.e. paths are hard-coded.

Bests,
Jan

**Comment by eugenwintersberger** [comment]
Update on this issue: the way how the pkg-config file creation is currently implemented works on Ubuntu Cosmic but cmake has issues to process this on all instances in the CI.

**Comment by jkotan** [comment]
The CI problem looks like

https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=31ca983c5

**Comment by jkotan** [comment]
or rather https://github.com/conan-io/conan/issues/3162

**Comment by jkotan** [comment]
Since the above problem is related to the CONAN issue (conan-io/conan#3162) I have add a code which skip creating pkgconfig configuration when CONAN=DISABLE is not set
