### ISSUE TITLE
cannot read string attribute with array size 1

### ISSUE THREAD

**Issue by yuelongyu** [ess-dmsc/h5cpp#309]
Hi,

I've encountered a problem that the h5cpp (v0.0.7) is no able to read string attribute which has array size 1. But if the array size shows as scalar, it works. 

>HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140552714533760:
  #000: ../../../src/H5A.c line 695 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 544 in H5A__read(): datatype conversion failed
    major: Attribute
    minor: Unable to encode value
  #002: ../../../src/H5T.c line 4844 in H5T_convert(): data type conversion failed
    major: Attribute
    minor: Unable to encode value
  #003: ../../../src/H5Tconv.c line 3193 in H5T__conv_vlen(): unable to convert between src and dest datatypes
    major: Datatype
    minor: Feature is unsupported
  #004: ../../../src/H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
terminate called after throwing an instance of 'std::runtime_error'

```C++
std::string base_class;
file.root().attributes["NX_class"].read(base_class); //works, the array size is scalar
std::cout<<base_class<<std::endl;

std::string testattr; 
file.root().attributes["testattr"].read(testattr); // doesn't work, the array size is 1
std::cout<<testattr<<std::endl;
```
![testfile](https://user-images.githubusercontent.com/2931050/40719797-ea534754-6414-11e8-8048-230e50678e93.png)

**Comment by yuelongyu** [comment]
Jan has tried another way and it works. It seems the datatype passed inside are wrong.
```C++
std::string testattr;
auto attr = file.root().attributes["testattr"];
attr.read(testattr,attr.datatype());
std::cout<<testattr<<std::endl;
```

**Comment by eugenwintersberger** [comment]
This look somehow strange to me. I will have a look on this.

**Comment by eugenwintersberger** [comment]
Actually how is the file created? Is this something done by h5cpp or by some other library.

**Comment by yuelongyu** [comment]
As I remembered, the simple_io.nxs is create with the simple_io.cpp. I added the testattr manually with HDFView and set the arrary size to be 1.

**Comment by yuelongyu** [comment]
@eugenwintersberger testcalib.nxs is created by your calibration tool.

**Comment by jkotan** [comment]
for the above file c++ with

    ATTRIBUTE "NX_class" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( H5S_UNLIMITED ) }
      DATA {
      (0): "NXroot"
      }
    }

reading in c++ fails

    #include <h5cpp/hdf5.hpp>
    #include <iostream>
    #include <string>


    int main()
    {
      hdf5::file::File file = hdf5::file::open("testcalib.nxs");
      auto r = file.root();
      auto attr = r.attributes["NX_class"];
      std::string buffer;
      attr.read(buffer); // gives unable to read attribute
      attr.read(buffer, attr.datatype());
      std::cout << buffer << std::endl;
      file.close();
      return 0;
    }


while similar python code works fine:

    import pninexus
    from pninexus import h5cpp

    f = h5cpp.file.open("testcalib.nxs")
    r = f.root()
    w =r.attributes["NX_class"].read()
    print(w)
    f.close()

That's because `Attribute::read()` in the python version is executed with `ArrayAdapter`. Does it mean that in order to make it working in C++ buffer should be of `std::vector<...>`  type?

**Comment by eugenwintersberger** [comment]
This is indeed strange. There should not be an issue with this. In particular because the type in the file is an variable length string. I will have a look on this. The Python wrapper does a bit more guessing work under the hood that's why it is working. Although I don't like this implicit conversion stuff too much as it can cause all kind of strange errors when making the wrong assumptions ;)

**Comment by matthew-d-jones** [comment]
This problem also affects scalar, fixed length strings. Using `attr.read(testattr,attr.datatype());` also works in this case.

**Comment by jkotan** [comment]
Scalar type was also tested in  added tests https://github.com/ess-dmsc/h5cpp/blob/issue_309_fix/test/attribute/attribute_read_io_test.cpp#L44

**Comment by matthew-d-jones** [comment]
Excellent, thank you!
