### ISSUE TITLE
how to get (un)signed from datatype

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#313]
I want to read an integer field from a file. I would like to learn what it its exact type. From `type` I can get if it is integer, from  `size` I get that it is 64 bits but how can I get if it is 'int64' or 'uint64' ?

**Comment by yuelongyu** [comment]
```C++
    std::string bit_depth_readout_path = std::string(":NXentry/:NXinstrument/:NXdetector/bit_depth_readout"); // value of the field 4294967295
    nexus::DatasetList fields = nexus::get_objects(file.root(),
                                                   nexus::Path::from_string(bit_depth_readout_path));


    std::cout<<"datatype test uint:"<<H5Tequal(static_cast<hid_t>(fields[0].datatype()),H5T_NATIVE_UINT)<<std::endl; // return true
    std::cout<<"datatype test int:"<<H5Tequal(static_cast<hid_t>(fields[0].datatype()),H5T_NATIVE_INT)<<std::endl; // return false
    std::cout<<"bit_depth_readout:"<<fields[0].dataspace().size()<<std::endl;
    
    unsigned int bit_depth_readout; // unsigned
    fields[0].read(bit_depth_readout);
    std::cout<<"unsigned value:"<<bit_depth_readout<<std::endl; // return 4294967295 correct value

    int bit_depth_readout_wrong; // signed
    fields[0].read(bit_depth_readout_wrong);
    std::cout<<"signed value:"<<bit_depth_readout_wrong<<std::endl; // return 2147483647 wrong value. This should be -1 instead of maximum value of signed integer.
```
I have created a field with maximum unsigned 32bit int value (2^32-1 = 4294967295). When reading with signed int, the singed value is wrong, in principle signed integer should return -1 instead of 2147483647. Is there an easy way to get the exact data type of the field before reading the value instead of using H5Tequal to compare with all HDF5 native type?

**Comment by martukas** [comment]
Maybe the problem described by @yuelongyu is a separate issue altogether?

**Comment by jkotan** [comment]
Yes, it would be good to create a new issue for it. @yuelongyu could you please create a new ticket for your comment.

**Comment by yuelongyu** [comment]
Done. A new ticket #324 is created.
