### ISSUE TITLE
h5cpp 0.0.8 does not build on jessie

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#333]
On debian jessie one need to add 

    #include <stdexcept>

when we use `runtime_error`. Otherwise, one get 

    /home/jkotan/sources/h5cpp/src/h5cpp/core/path.cpp:207:11: error: ‘runtime_error’ is not a member of ‘std’
         throw std::runtime_error("paths must both be absolute or relative to have common base!");
           ^

**Comment by martukas** [comment]
Is that debian 8? We only test 9 on our Jenkins.
Release 008 was premature anyways. You could submit a fix and we will have it in for 009 which we should release soon.

**Comment by jkotan** [comment]
Yes. We've got still most of the boxes on debian 8.

**Comment by jkotan** [comment]
fixed in #334
