### ISSUE TITLE
test from SignedInteger/0, where TypeParam = char fails on armhf

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#336]
running tests on `armhf` I get the following error:

    [----------] 1 test from SignedInteger/0, where TypeParam = char
    [ RUN      ] SignedInteger/0.Signed
    /home/jkotan/deb-sources/h5cpp/test/datatype/integer_test.cpp:105: Failure
          Expected: t.is_signed()
          Which is: false
    To be equal to: true
    [  FAILED  ] SignedInteger/0.Signed, where TypeParam = char (1 ms)
    [----------] 1 test from SignedInteger/0 (1 ms total)

It looks like the c++ standard does not specify if plain `char` is `signed` or `unsigned`.

So maybe it would be good to relax our tests.

**Comment by eugenwintersberger** [comment]
According to the [C++ reference](https://en.cppreference.com/w/cpp/language/types) Jan has a good point here. The signedness of char depends on the compiler and the target platform.
