### ISSUE TITLE
read out integer value error in attribute

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#347]
it is a similar ticket to #323 but related to attributes, i.e. when you read `unsigned int` with very large value  to `int` buffer you loose the information, i.e. you a get wrong value. `h5cpp` should at least throw exception. Similarly opposite way round. 

Other option would be to use a fix from #309 for int types. Then the following test would work:

    TEST_F(AttributeScalarIO, test_int_overflow)
    {
      unsigned int uintmax= 4294967295;
      attribute::Attribute a = root_.attributes.create<unsigned int>("uintmax");
      a.write(uintmax);
      int int_read_back;
      unsigned int uint_read_back;
      a.read(uint_read_back);
      EXPECT_EQ(uintmax, uint_read_back);
      a.read(int_read_back);
      EXPECT_EQ(uintmax, static_cast<unsigned int>(int_read_back));
    }

i.e. `unsigned int` big value is converted to `int` negative value, without loosing the information, and can be casted back by `static_cast<unsigned int>`.

**Comment by eugenwintersberger** [comment]
I am actually not sure what would be a good solution. In fact trying to read an unsigned value to an integer value is definitely risky. It could work if the unsigned value is small enough to fit into the range of the signed integer. However, in any other case you might be lost. I would rather go with the had approach and throw an exception or leave this risk up to the user. 

Is there a particular use case why you want to read an unsigned integer to an integer variable?

**Comment by jkotan** [comment]
An exception for me is also OK

**Comment by eugenwintersberger** [comment]
This is difficult to handle. As we know only at runtime (when the user code is confronted with a specific file) whether or not the dataset or attribute we try to read is of a signed or unsigned integer type we cannot catch this at compile time. Consequently we would either need something like a *conversion policy* which at runtime decides what conversions are allowed are we need some runtime logging which raises a warning. Throwing an exception is quite a harsh and may breaks a program (again a policy would help here). No idea how to deal with such a situation actually.

**Comment by eugenwintersberger** [comment]
You have to check type compatibility on application level. This is something we unfortunately cannot do on the library level.
