### ISSUE TITLE
`bool` is equivalent to `unsigned char`

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#354]
In the current implantation the c++ `bool` type is represent by `H5T_NATIVE_HBOOL`.
On the other hand `H5T_NATIVE_HBOOL` is equivalent to  `H5T_NATIVE_UINT8` which in `h5cpp` is `unsigned char`.
Thus, `bool` and `unsigned char` are the same. This BRAKES mapping to NeXus Format, i.e. in the nexus format NX_BOOLEAN and NX_UINT are different types and they should be recognizable (especially that in c++ one can see differences between `bool` and `unsigned char`).

So, in my opinion currently it is not possible to use the `h5cpp` library to write/read the proper NeXus files.

Of course there are possibilities to fix it:

- in the old  version of `libpniio`  the c++ bool type was represented by none `H5T_NATIVE_HBOOL`  hdf5 type.
- in h5py the c++ bool types are represented by enums. 

One can see more details in https://github.com/ess-dmsc/h5cpp/issues/260  Its branch  contains examples of bool data files from `h5py` and `libpniio` (https://github.com/ess-dmsc/h5cpp/tree/issue_260/test).

So I think it would be good `h5cpp` could read both versions of the data and use one of them to store bools.

Using `H5T_NATIVE_HBOOL` is useless for people using nexusformat, e.g.

    #include <h5cpp/hdf5.hpp>
    #include <iostream>

    int main()
    {

      hdf5::property::FileAccessList fapl;
      fapl.close_degree(hdf5::property::CloseDegree::STRONG);
      hdf5::property::FileCreationList fcpl;
      auto nexus_file = hdf5::file::create("testbool.h5",
				     hdf5::file::AccessFlags::TRUNCATE, fcpl, fapl);
      int hdf5_version =  123;
      auto type1 = hdf5::datatype::create<bool>();
      auto type2 = hdf5::datatype::create<unsigned char>();
      hdf5::dataspace::Scalar space;

      auto r1 = nexus_file.root();
      r1.attributes.create("HDF5_bool", type1, space).write(true);
      r1.attributes.create("HDF5_uchar", type2, space).write(true);

      std::cerr << H5Tequal(static_cast<hid_t>(type1),H5T_NATIVE_HBOOL) << std::endl;
      std::cerr << H5Tequal(static_cast<hid_t>(type2),H5T_NATIVE_HBOOL) << std::endl;
      r1.close();

      return 0;

    }

shows you cannot recognized if it is `bool` or `unsigned char`.

**Comment by eugenwintersberger** [comment]
I am not sure if I have already mentioned this but the bool thing seems to be an issue of the HDF5 C-library (in particular the boolean type is not really working at least on Debian 8 systems). Providing support for enumerations should be fairly easy however, I am not sure if the conversion should be done automatically. I would think about something like a plugin mechanism to make this happen on demand. We could define type traits for each format for storing booleans and than decide at compile time which choose as the default.

**Comment by jkotan** [comment]
Hi @eugenwintersberger , I do not understand why you need a plugging mechanism. 

If we are going to implement `BOOLEAN`s as `Enum` you do not want to cast it into c++ `bool` type because no one wants to implement an iterator in bit resolution for for `std::vector<bool>`. So it is better to left it as an `Enum`.  But it would be good to have it in `h5cpp` to avoid duplication of client code where he/she defines  `TypeTrait` for `EBool` (Enum Bools) again and again. 

Actually, because of `std::vector<bool>` problem it is better not to use c++ bool but predefined ones, also for bool integer-like types (similarly to the code in the old `pniiio` library - that why you did it there ).
