### ISSUE TITLE
empty string array field is not readable

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#355]
contratry to other fileds, e.g. `int` array fields,  empty `string` array fields are not readable, e.g. the following code

    #include <h5cpp/hdf5.hpp>
    #include <iostream>

    int main()
    {

      hdf5::property::FileAccessList fapl;
      fapl.close_degree(hdf5::property::CloseDegree::STRONG);
      hdf5::property::FileCreationList fcpl;
      auto nexus_file = hdf5::file::create("teststr.h5",
				     hdf5::file::AccessFlags::TRUNCATE, fcpl, fapl);
      hdf5::property::LinkCreationList lcpl;
      hdf5::property::DatasetCreationList dcpl;
      dcpl.layout(hdf5::property::DatasetLayout::CHUNKED);
      dcpl.chunk({1});
      hdf5::property::DatasetAccessList dapl;

      auto string_type = hdf5::datatype::create<std::string>();
      auto int_type = hdf5::datatype::create<int>();
      auto r1 = nexus_file.root();
      hdf5::Dimensions s = {0}, m = {hdf5::dataspace::Simple::UNLIMITED};
      hdf5::dataspace::Simple sp(s, m);
      auto ds1 = hdf5::node::Dataset(r1,
				     hdf5::Path("int"),
				     int_type,
				     sp,lcpl,dcpl, dapl);
      auto ds2 = hdf5::node::Dataset(r1,
				     hdf5::Path("str"),
				     string_type,
				     sp,lcpl,dcpl, dapl);

      std::vector<int> buffer1 ; 
      std::vector<std::string> buffer2; 
      ds1.read(buffer1);
      ds2.read(buffer2);
      r1.close();

      return 0;

    }

throws

    HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140164416621440:
      #000: ../../../src/H5D.c line 747 in H5Dvlen_reclaim(): invalid argument
	major: Invalid arguments to routine
	minor: Bad value
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Error reclaiming memory from variable length string data in dataset [/str]!
    Aborted

when I try to read the empty  string array field, i.e. `ds2`.  For  the empty int field, i.e. `ds1` it works
and it returns an empty vector.

**Comment by eugenwintersberger** [comment]
I guess the issue here is the relcaiming process of the internal buffers which does not take place for other data types. It's rather a string thing. An appropriate solution would be to check in advance if the dataset (or attribute) contains data and return an appropriate result if it is empty.
