### ISSUE TITLE
add support for reading bools defined in h5py as enums

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#357]
I think a good idea would be to add support for h5py bools.  It would a workaround for:

1) reading std:vector<bool>  which operates on bits (mentioned in #260)
2) problem in recognizing between `int` and `bool` (#354)

So it would be nice to have `enum bool` type , e.g. `datatype::EBool` already defined in h5cpp.
In this way user do not have to define it each time he want to use it.

The issue was splitted from #260.

**Comment by eugenwintersberger** [comment]
Hi Jan. I guess we have discuss this in more detail. I totaly agree with you and I guess I have a solution that would fit all needs.
