### ISSUE TITLE
reading image data in plane h5cpp slower than reading with h5cpp python bindings

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#379]

**Comment by jkotan** [comment]
I've just made benchmark comparing  reading image data in plane h5cpp 
```cpp
#include <h5cpp/hdf5.hpp>
#include <vector>

int main() {
  std::string filepath = "/home/jkotan/scratch/files/watertest_00563_b.nxs";

  auto file = hdf5::file::open(filepath, hdf5::file::AccessFlags::READONLY);
  auto root = file.root();
  auto dataset = root.get_dataset("/entry/instrument/pilatus/data");
  std::vector<uint16_t> data(353409408L);
  dataset.read(data);
  return 0;
}
```

and it seem 17 times slowers than  python

```python
from pninexus import h5cpp

f = h5cpp.file.open(
    "/home/jkotan/scratch/files/watertest_00563_b.nxs",
    h5cpp.file.AccessFlags.READONLY)
rt = f.root()
ds = rt.get_dataset(h5cpp.Path("entry/instrument/pilatus/data")) 
dt = ds.read()
f.close()
```

i.e.
```bash

jkotan@haso228jk:~/sources/h5cpptest$ time ./test_readdata_h5cpp2

real	0m34.275s
user	0m34.224s
sys	0m0.049s
```

```bash
jkotan@haso228jk:~/sources/h5cpptest$ time python test_readdata_h5cpp.py 

real	0m2.156s
user	0m2.091s
sys	0m0.065s
```

The data has (33, 2672, 4008) shape  and `uint16` type, .i.e.
```
            DATASET "data" {
               DATATYPE  H5T_STD_U16LE
               DATASPACE  SIMPLE { ( 33, 2672, 4008 ) / ( H5S_UNLIMITED, H5S_UNLIMITED, H5S_UNLIMITED ) }
               DATA {
...

```

**Comment by eugenwintersberger** [comment]
This is strange. Is is possible that you somehow can share the file?

**Comment by jkotan** [comment]
Yes, it is strange . I've put the file to  http://www.desy.de/~jkotan/h5cpptest/watertest_00563_b.nxs

**Comment by eugenwintersberger** [comment]
How did you build the C++ program (compiler options, etc.)?

**Comment by jkotan** [comment]
```bash
g++ test_readdata_h5cpp2.cpp -lh5cpp -lboost_system -lhdf5 -I /usr/include/hdf5/serial/ -L /usr/lib/x86_64-linux-gnu/hdf5/serial/ -o test_readdata_h5cpp2
```

**Comment by jkotan** [comment]
BTW, It would be much simpler to compile with the `pkgconfig` support #302.

**Comment by jkotan** [comment]
It looks like is it issue with shape of the buffer. Reading  to linear buffer takes much longer, i.e.

```python
from pninexus import h5cpp
import numpy

f = h5cpp.file.open(
    "/home/jkotan/scratch/files/watertest_00563_b.nxs",
    h5cpp.file.AccessFlags.READONLY)
rt = f.root()
ds = rt.get_dataset(h5cpp.Path("entry/instrument/pilatus/data"))
buffer = numpy.zeros(shape=(353409408), dtype='uint16')
dt = ds.read(buffer)
```
takes ~ 33s while for

```python
from pninexus import h5cpp
import numpy

f = h5cpp.file.open(
    "/home/jkotan/scratch/files/watertest_00563_b.nxs",
    h5cpp.file.AccessFlags.READONLY)
rt = f.root()
ds = rt.get_dataset(h5cpp.Path("entry/instrument/pilatus/data"))
buffer = numpy.zeros(shape=(33, 2672, 4008), dtype='uint16')
dt = ds.read(buffer)
```
it is enough ~2s.

**Comment by jkotan** [comment]
I've just noticed that if you call read() with `datatype` `dataspace` parameters of read dataset

```c++
#include <h5cpp/hdf5.hpp>
#include <vector>

int main() {
  std::string filepath = "/home/jkotan/scratch/files/watertest_00563_b.nxs";

  auto file = hdf5::file::open(filepath);
  auto root = file.root();
  auto dataset = root.get_dataset("/entry/data/pilatus");
  std::vector<unsigned short int> data(353409408L);
  auto datatype = dataset.datatype();
  hdf5::dataspace::Simple dataspace(dataset.dataspace());

  
  dataset.read(data, datatype, dataspace, dataspace);
  return 0;
}
```
it works fast (~2s). So implementation of `read(buffer)` is wrong.
That reminds me https://github.com/ess-dmsc/h5cpp/issues/313 which issomehow connected ;)

**Comment by eugenwintersberger** [comment]
I definitely should have a look at this with a profiler. This is rather strange.

**Comment by jkotan** [comment]
Moreover, similar issue we get with reading slices, i.e.

```c++
#include <h5cpp/hdf5.hpp>
#include <vector>


int main() {
  std::string filepath = "/home/jkotan/scratch/files/watertest_00563_b.nxs";

  auto file = hdf5::file::open(filepath);
  auto root = file.root();
  auto dataset = root.get_dataset("/entry/data/pilatus");
  auto datatype = dataset.datatype();
  hdf5::dataspace::Simple dataspace(dataset.dataspace());
  const auto dimensions = dataspace.current_dimensions();
  std::vector<unsigned short int> data(dimensions[1]*dimensions[2]*11);

  hdf5::Dimensions frameoffset{10, 0, 0};
  hdf5::Dimensions frameblock{11, dimensions[1], dimensions[2]};
  hdf5::dataspace::Hyperslab selectedFrames{frameoffset, frameblock};
  // 0) Works
  hdf5::dataspace::Simple dataspace2(hdf5::Dimensions{11, dimensions[1], dimensions[2]});
  dataset.read(data, datatype, dataspace2, selectedFrames);

  // 1)  Slow
  // dataset.read(data, selectedFrames);

  // 2)  Segmentation fault
  //  selectedFrames.apply(dataspace, hdf5::dataspace::SelectionOperation::SET);
  //  dataset.read(data, datatype, dataspace, selectedFrames);
  return 0;
}
```
Above, Only 0) option works correctly.  The default command with `read(buffer, selection)` is ~ 17 slower while with 2) I get seg fault (probably it is not allowed).

**Comment by jkotan** [comment]
The most of the time takes call to `H5Dread(...)` in `Dataset::read_contiguous_data()`.

Different is in `H5Dread` parameters, i.e. 
for 
```c++
dataset.read(data, datatype, dataspace, dataspace);
```
we have `hid_t`'s
```
this 500000000000000
mem_type 30000000000013a
mem_space 400000000000003
file_space 400000000000003
dtpl a00000000000031
```

while for
```c++
dataset.read(data);
```
we have
```
this 500000000000000
mem_type 30000000000013a
mem_space 400000000000002
file_space 400000000000003
dtpl a00000000000038
```
So it looks like `mem_space and `file_space` are not compatible so `H5Dread` has to convert them.

**Comment by jkotan** [comment]
To sum up:

```c++

#include <h5cpp/hdf5.hpp>
#include <vector>

int main() {
  std::string filepath = "/home/jkotan/scratch/files/watertest_00563_b.nxs";

  auto file = hdf5::file::open(filepath);
  auto root = file.root();
  auto dataset = root.get_dataset("/entry/data/pilatus");
  std::vector<unsigned short int> data(353409408L);
  auto datatype = dataset.datatype();
  hdf5::dataspace::Simple dataspace(dataset.dataspace());
  auto dims = dataspace.current_dimensions();
  hdf5::dataspace::Simple dataspace1(hdf5::Dimensions {dims[0], dims[1], dims[2]});
  hdf5::dataspace::Simple dataspace2(hdf5::Dimensions {dims[0] * dims[1] * dims[2]});

  // Fast: OK                                                                                                                              
  dataset.read(data, datatype, dataspace1, dataspace1);
  // SLOW: case of read(buffer);                                                                                                           
  // dataset.read(data, datatype, dataspace2, dataspace1);                                                                                 
  // SLOW:                                                                                                                                 
  // dataset.read(data, datatype, dataspace1, dataspace2);                                                                                 
  // SLOW:                                                                                                                                 
  // dataset.read(data, datatype, dataspace2, dataspace2);                                                                                 

  return 0;
}
```
the only fast case is when we take the default `memory dataspace` from `file dataspace` (not from buffer). Otherwise H5Dread spend a lot of time to convert them.

**Comment by eugenwintersberger** [comment]
I do not really understand what should be converted there. In addition I do not think that the different Id's give us any hint whether or not the dataspaces are compatible. In particular what would an incompatible dataspace mean. I would understand if the datatypes where different which is obviously not the case. I will have a look on this on Saturday.

**Comment by eugenwintersberger** [comment]
Ok. I slowly understand what goes wrong here. Need to think about a good solution. Should not be too hard to solve.

**Comment by jkotan** [comment]
Comparing Id parameters the most important thing is that the type id's are the same  so it should be something related with dataspaces. 
In my option the problem is that we try to read to a linear buffer with rank 1 (which defines default memory_space in h5cpp) while our file dataspace has rank 3.
Since shapes are different `H5Dread` function iterates over all elements of the data (which takes time).

BTW,  in `hdf5` the default `memory_space` is taken from `file_space` (not from the memory buffer)
https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/src/H5Dio.c#433

**Comment by eugenwintersberger** [comment]
You are right with the iteration step involved in order to reorder the data. You are also right with the default behavior in HDF5. We could go for this but maybe should introduce a size check in advance in order to ensure that the size of the target buffer at least fits the size of the file-dataspace.

Concerning #313: the problem there was the datatype which is much more dangerous as you absolutely have to convert types to get the correct result (float->double for instance). So I guess we can happily go with the HDF5 default behavior here and use the file-dataspace as long as we check the size of the target instance.

Actions to take:
* in case of no memory-dataspace is provided by the user we use the default file space (or the one established by a selection)
* we need to extend the dataspace trait for a size(const T&) size method in order to get the size of T

The difficult part here will be to extract the new dataspace in case a dataspace where a selection is applied.

**Comment by eugenwintersberger** [comment]
You need the `size()` method to check the size of the buffer. Basically you want to do something like this in any of the read methods 
```cpp
using TraitType = TypeTrait<BufferType>;
size_t file_size = ....;
if(file_size != TraitType::size(buffer))
{
  //throw an exception here
}
```
