### ISSUE TITLE
missing API for read compression level and type when you read a dataset

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#388]
It would be nice to have possibility to read a compression level and a compression type as well a shuffle flag.
There is API  to set  a level and a shuffle flag via `DatasetCreationList` and `Deflate` but reading them back from the dataset seems to be only accessible via native API.

**Comment by eugenwintersberger** [comment]
Hi Jan, I am currently working through the original HDF5 C-examples and try to provide C++ versions for them. I already have seen that we miss some features in the filters API. I will try to handle this asap.

**Comment by zjttoefs** [comment]
Handling of filter stack leaves something to be desired.
