### ISSUE TITLE
Comparison with HighFive

### ISSUE THREAD

**Issue by wolfv** [ess-dmsc/h5cpp#398]
We're currently using the HighFive library as a modern C++ wrapper. 
I was wondering if you were aware of it's existence?
Are there any major differences?

**Comment by eugenwintersberger** [comment]
At least I was not aware of this library. Thus I cannot tell you what are the major differences. But I most probably will have a look on it.

**Comment by eugenwintersberger** [comment]
Ok. I had a closer look on the HighFive library.  There are two major differences I can see in comparison with h5cpp. 

`HighFive` seems to be developed within the framework of a particular project and thus supports a particular subset of the HDF5 C-API's functionality. Our intention is however to provide the full functionality of the C-API. Though, we have still some work ahead of us to achieve this goal, the entire design of `h5cpp` was tailored towards this goal. This is also the reason why our interface currently looks maybe a bit low level.

The second aspect which, at least to me, separates `h5cpp` from `HighFive` is our approach towards STL compatible interfaces. This is particularly true for structural operations like searching through a tree of HDF5 objects. With `h5cpp` you can use STL algorithms to search and manipulate the HDF5 object tree. In particular the searching feature is something I find particularly useful. 

I hope this helps.

**Comment by wolfv** [comment]
Thanks, that's really good to know.

Would be cool to see some collaboration :)

**Comment by eugenwintersberger** [comment]
Collaboration is always good. Do you have something specific in mind?

**Comment by wolfv** [comment]
Nope! :) We've used HighFive as part of `xtensor-io`, and I remember researching HDF5 libraries in C++ for that purpose. Just wanted to see wether there is awareness of one-another.

**Comment by wolfv** [comment]
https://github.com/QuantStack/xtensor-io
