### ISSUE TITLE
version in CMakeLists.txt is still 0.1.0

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#401]
it looks like for releases > 0.1.0 the version variable in CMakeLists.txt is still 0.1.0.

**Comment by jkotan** [comment]
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d97a1cf..b1226d7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,7 +1,7 @@
 cmake_minimum_required(VERSION 3.0.0)
 project(h5cpp
     LANGUAGES CXX C
-    VERSION 0.1.0
+    VERSION 0.1.3
     )
```

**Comment by eugenwintersberger** [comment]
Hell yeah. You are right. I will fix this right away.

**Comment by martukas** [comment]
Sorry this was my fault. I made a few patch releases, which were not semantically patches at all. So, actually, since the next milestone is 0.3.0, maybe we should just make this 0.2.0 and release that as a version before we proceed to our sprint?

**Comment by eugenwintersberger** [comment]
Fine for me. Just change it and close the ticket ;)

**Comment by jkotan** [comment]
No problem. For 0.1.3 I can patch it on the debian package level (otherwise the deb package interferes with the 0.1.0 version)
