### ISSUE TITLE
Incorrect APT source linked in docs for Ubuntu

### ISSUE THREAD

**Issue by eudoxos** [ess-dmsc/h5cpp#409]
https://ess-dmsc.github.io/h5cpp/users_guide/installing.html#debian-and-ubuntu-users is advising to download http://repos.pni-hdri.de/bionic-pni-hdri.list with repository information. This file contains:

    deb http://repos.pni-hdri.de/apt/ubuntu bionic main

 which results in 404; the correct entry should be

   deb http://repos.pni-hdri.de/apt/debian bionic main

as the archive puts both debian and ubuntu releases into the same (debian) directory. This might be the case for other Ubuntu releases as well.

**Comment by zjttoefs** [comment]
Confirmed the /ubuntu tree only has (ancient) packages for trusty and precise. 
I guess correcting the instructions to use the same .list for both ubuntu and debian is best.
But maybe you also want to fix something up on the repo side, @eugenwintersberger?

**Comment by jkotan** [comment]
Thanks. I've just fixed it.
