### ISSUE TITLE
two different h5cpp projects

### ISSUE THREAD

**Issue by eudoxos** [ess-dmsc/h5cpp#411]
Sorry for the stupid remark, though... There are two projects called h5cpp, one is yours and the other is Steven Varga's https://github.com/steven-varga/h5cpp (also https://h5cpp.org). Fortunately at least, you live in `hdf5::` and the other in `h5::`. Could you perhaps mention the possible confusion in the documentation? I was puzzled for a while, others might be, too. Thanks!

**Comment by eugenwintersberger** [comment]
Hi @eudoxos. Sorry for my late reply. You are right. This situation is a bit confusing. We are well aware of the project of Steve. When we choose the name for the project we were not aware about Steve's project. I will have some time do work on h5cpp in the next two weeks and will make a comment in the Readme in the repository.

**Comment by zjttoefs** [comment]
It is fair to point out that Eugen chose the name and had external collaborators to this h5cpp at least half a year before Steven made the first commit to his project. At that time searching for h5cpp on github would have found this for sure.

**Comment by kc9jud** [comment]
It's actually worse... there are three projects named h5cpp, though Steven Varga renamed his first h5cpp to h5cpp11 at some point and started over: https://github.com/steven-varga/h5cpp11. Both of the other projects are more recent than this one, however.
