### ISSUE TITLE
Add ExternalFilter class

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#415]
We get request from our users to have a gerenal filter class for external filters where in its constractor one can define a filter type id and compression parameters.

It can be quite useful for users which use LZ4 (32004) or BitShuffle (32008) which are much faster than the standard deflate. With the requested ExternalFilter class they do not have to create filter class everytime they use external filters.

**Comment by eugenwintersberger** [comment]
@jkotan - can you close this issue.
