### ISSUE TITLE
warning: explicitly defaulted move assignment operator is implicitly deleted

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/h5cpp#417]
This defaulted move assignment operator is implicitly deleted so generates a warning in Clang 8:
```
Dataspace &operator=(Dataspace &&type) = default;
```
Notes from the compiler:

- Move assignment operator of 'Dataspace' is implicitly deleted because field 'selection' has a deleted move assignment operator

- Copy assignment operator of 'SelectionManager' is implicitly deleted because field 'space_' is of reference type

**Comment by eugenwintersberger** [comment]
This makes sense to me. I will have a look on this later this week.

**Comment by SkyToGround** [comment]
Fixed by removing the line `Dataspace &operator=(Dataspace &&type) = default;`.
