### ISSUE TITLE
Create a new (release) version of  h5cpp

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#427]
We have implemented several fixes for compile issues in the h5cpp library, including updating to hdf5 version 1.10.5. It is thus a good time to create a new release of h5cpp. @martukas, @eugenwintersberger  do you want to do this or should I?

**Comment by jkotan** [comment]
Hi, 

Since we had requests at DESY to make a new release last  weak  and there was no traffic on bug tracker I've just created tag and made release v0.3.0.
I hope it is OK with you.
