### ISSUE TITLE
Migrate to google test

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#43]
I have already begun this in the gtest branch.
./test/CMakeLists.txt has a short section of the find-replace steps that are needed to easily convert from boost unit test. Fixtures may require additional work.
Most tests and add_subdirectory statements are commented out pending conversion to gtest.

**Comment by eugenwintersberger** [comment]
I found a reasonable googltest (version 1.8.0) package for conan. So building the code on Windows including tests should not be too difficult.
