### ISSUE TITLE
Half-precision float support?

### ISSUE THREAD

**Issue by jyhengcoder** [ess-dmsc/h5cpp#434]
I intend to use the Half precision floating-point format for storing data that do not need as much precision in order to save space. So does this code support half-precision float storage?

**Comment by jkotan** [comment]
Hi @jyhengcoder,
Yes sure. The C++ float is mapped to  `H5T_NATIVE_FLOAT` type: [type_trait](https://github.com/ess-dmsc/h5cpp/blob/master/src/h5cpp/datatype/type_trait.hpp#L174)

**Comment by jkotan** [comment]
In  HDF5 you do not have fp16 but only fp32.

**Comment by jyhengcoder** [comment]
Thanks for your quick answer. But h5py provides an option to store data as fp16.
```
file.create_dataset(key, data=data,  dtype = np.float16)
```
No predefined type provided for fp16 storage on the official documentation of hdf5 for C++ , linking here https://support.hdfgroup.org/HDF5/doc1.8/RM/PredefDTypes.html.

So I want to know, is there any methods for me to use fp16 in hdf5-C++?

**Comment by jyhengcoder** [comment]
hi! @jkotan 
I found in hdf5 has an C interface named `H5Tset_precision`, Does this interface have a corresponding implementation in h5cpp?

**Comment by jkotan** [comment]
In hdf5 you can define also types beyond its standard. So if you want to use  fp16 IEEE you can define it in the way described at [HDF forum](https://forum.hdfgroup.org/t/half-precision-floating-point-format-implemented/1551). We don't not have a type class which corresponds to  fp16 IEEE but if you define one with proper datatype traits it should be possible to use it with h5cpp as well.

**Comment by jyhengcoder** [comment]
> In hdf5 you can define also types beyond its standard. So if you want to use fp16 IEEE you can define it in the way described at [HDF forum](https://forum.hdfgroup.org/t/half-precision-floating-point-format-implemented/1551). We don't not have a type class which corresponds to fp16 IEEE but if you define one with proper datatype traits it should be possible to use it with h5cpp as well.

OK, thanks for your answer. I will try the method in HDF forum and now close this issue.

**Comment by jkotan** [comment]
It would be nice to add methods to changing datatype properties, e.g. precision. It is also useful for NBit filter #389
