### ISSUE TITLE
CMake: Use build interface with target_include_directory()?

### ISSUE THREAD

**Issue by FlorianBen** [ess-dmsc/h5cpp#449]
I usually use h5cpp in my projects by using git submodule, and then adding h5cpp folder directly from my top level CMake file.

Unfortunately there is no build interface defined for target_include_directory, so if a target consumes h5cpp in the same build, then it will not find the h5cpp headers (and will not compile). Is it possible to add a line like `PUBLIC` or  `INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>` there?
https://github.com/ess-dmsc/h5cpp/blob/90107db05ba8615210e40e4c062b082ff9c2cdab/src/h5cpp/CMakeLists.txt#L58-L63

**Comment by eugenwintersberger** [comment]
Hi Florian. This sounds like a reasonable suggestion. Since you already presented a solution you may can also issue a pull request for this. If not I can try to fix this next weekend.
