### ISSUE TITLE
add wrapper for H5LTopen_file_image function

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#456]
It would be good to wrap 
```
hid_t H5LTopen_file_image( void *buf_ptr, size_t buf_size, unsigned flags ) 
```
which allows to read an hdf5 file directly from memory.
It is useful for reading files e.g. sent via network.

**Comment by eugenwintersberger** [comment]
Sounds like a very reasonable proposal. Since I am currently quite busy with the new tests, can you maybe write a short proposal how this API should look like?

**Comment by jkotan** [comment]
Hi Eugen, I've proposed the API in PR #459
