### ISSUE TITLE
Implemement getter for dataset extent

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#48]
With signature:
Dimensions Dataset::extent() const;

**Comment by eugenwintersberger** [comment]
You can obtain the extent of a dataset via its dataspace (using the `dataspace()` method). The reason is that it would otherwise not be clear what extent you want. The current dimensions? The maximum dimensions?

**Comment by martukas** [comment]
Ok, I've found the way.
So, it's Simple(dataset.dataspace()).maximum_dimensions() ?
When would a dataset not have a Simple type of dataspace but something else?

**Comment by eugenwintersberger** [comment]
When you write a single scalar value for instance you could use a `Scalar` dataspace. So to be save you would first have to ask what kind of dataspace our dataset has.

**Comment by martukas** [comment]
What's the point of a scalar dataset? How is that better than an attribute? :)
