### ISSUE TITLE
Updating Jenkins build configuration

### ISSUE THREAD

**Issue by amues** [ess-dmsc/h5cpp#484]
@eugenwintersberger, @jkotan, we are evaluating the possibility of deprecating some of the build node Docker images we use in our Jenkins builds. The idea is to drop `centos7` `debian9` and `ubuntu1804`, so we only support the following four images:

- `centos7-gcc8`
- `debian10`
- `ubuntu1804-gcc8`
- `ubuntu2004`

Would this be fine with you?

**Comment by jkotan** [comment]
Sure. Good idea.

**Comment by eugenwintersberger** [comment]
I am fine with this. Sounds like a reasonable decision.

**Comment by amues** [comment]
Thank you for the information. I'll send a pull request with the Jenkins build update in the near future.
