### ISSUE TITLE
Implementation of the hdf5::node::link functions

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#5]
Function prototypes are declared in

src/include/h5cpp/node/functions.hpp

Taks
* check the declaration 
* add convenience wrappers if required 
* implement functionality
* write unit tests

**Comment by martukas** [comment]
1. There are still likely edge cases with absolute or relative paths.
2. Parent file comparison should be done using object_id rather than file path, pending implementation of comparison operator for file::File
3. Lacking tests

**Comment by martukas** [comment]
Mostly good. Q2 solved, but this still needs better testing, which I leave for #36
