### ISSUE TITLE
pkg-config generation fails with `WITH_BOOST=OFF`

### ISSUE THREAD

**Issue by planetmarshall** [ess-dmsc/h5cpp#502]
I didn't address this in my PR (#501) - but the pkg config generation script doesn't work as it requires all of the target properties to be resolved at **configuration time**, whereas many of the properties (specifically for the `std::filesystem` configuration) are only resolved at **build time**, so the resulting `h5cpp.pc` file just contains generator expressions.

If you want to generate a configuration file with generator expressions you need to use [`file(GENERATE...)`]( https://cmake.org/cmake/help/latest/command/file.html?highlight=generator%20expressions#generate)

**Comment by eugenwintersberger** [comment]
This entire things requires some review.

**Comment by planetmarshall** [comment]
It's up to you of course but *if* this were my project, I might consider abandoning direct pkg-config support entirely and just supporting CMake. I guess it depends what your downstream users require.

**Comment by jkotan** [comment]
Pkg-config is required by our users in DESY. Therefore, we should keep it

**Comment by eugenwintersberger** [comment]
`pkg-config` is extremely common in the Linux world and can be used by virtually any build system. I agree that CMake package files are far more powerful but the only build system supporting them, aside from `cmake`, is `meson`. So I think supporting `pkg-config` is currently absolutely necessary. Let's see how things evolve in future and maybe one day we can get rid of it ;)

What we definitely have to improve is the way the files get built. I hope I can merge Andrews PR branch into my current working branch and then do a merge with master next weekend. Afterwards a review of the entire build system is I guess a good thing to do. But first I would like to read through Andrews changes.

**Comment by jkotan** [comment]
@planetmarshall thank you for the report. I've decided to change generator expressions to if statements because linker options are visible during cmake configuration and the solution is much easier
