### ISSUE TITLE
Get rid of all-caps enumerations

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#503]
This is a major thing as it will definitely break the current API. We thus should consider this as a move towards Release 1.0. 
During my efforts moving the tests to Catch2 I stumbled upon this problem on Windows. And indeed, it is rather stupid that we defined the enumerations as all caps as this is somehow the defacto standard for preprocessor definitions. 
The C++ core guideslines use a lower case notation for the enumerations. This might cause problems too in some cases but only when we would like to use keywords as enumerations (like `true` and `false` in `EBool`). In general this would be the better choice and thus we should do this rather early than latter.

DOD:
- all enumerations use lower-case names

**Comment by planetmarshall** [comment]
Yes this has led to a couple of build problems related to macros defined in system headers, eg

* MacOS defines `TRUE` and `FALSE` macros
* Windows GDI defines an `OPAQUE` macro.

**Comment by jkotan** [comment]
I agree we should change a notation for the enumerations. However, the lower case notation (like `true` and `false` in `EBool`) may cause other problems i.e. `true` and `false` are boolean literals in c++. So either we should change `true` `false`  (e.g. `etrue`,  `efalse`) to other words or use the upper camel case convention (`True` and `False` for `EBool`). What do you think?

**Comment by jkotan** [comment]
In #392 it was decided to use the Google enum convention with `k` replaced by `e` so It would mean `EBool::eTrue` and `EBool::eFalse` ? Shall we stick to it?

**Comment by eugenwintersberger** [comment]
I would prefer upper case literals and keeping the scope. I do not know if the `e` prefix is really necessary if we keep the scope. So I would prefer `EBool::True` if there is no good argument against it.

**Comment by jkotan** [comment]
I also like `EBool::True`

**Comment by planetmarshall** [comment]
> In #392 it was decided to use the Google enum convention with `k` replaced by `e` so It would mean `EBool::eTrue` and `EBool::eFalse` ? Shall we stick to it?

My 2 cents - The Google convention is a bit old fashioned and feels a bit like Hungarian Notation. It seems unnecessary to prefix the name when we have scoped enums. Perhaps it's a hangover from C++98 before scoped enumerations.

**Comment by eugenwintersberger** [comment]
@planetmarshall totally agree with you on that. I guess we can simply drop the `e` prefix.
