### ISSUE TITLE
The unit tests fails when using h5cpp with the latest version of the hdf5 library

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#506]
This was tested with version 1.12 of the hdf5 library. This is at least partially caused by the use of outdated static hdf5 files in the unit tests.

**Comment by jkotan** [comment]
@eugenwintersberger, would you like to merge the fix to master?

**Comment by eugenwintersberger** [comment]
Hi Jan. I can do that tomorrow. However, how would we integrate the test? Currently, the builds for the Linux distributions use the HDF5 version shipped with their repositories. Do we want to add a new test?

**Comment by jkotan** [comment]
Good question. I'm not so sure. Maybe we can add one more tests for 1.12 (e.g. deb11) or change e.g. only ubuntu20.04 tests to 1.12.

**Comment by eugenwintersberger** [comment]
Seems that I have some regression here. Will have a look on this during the weekend.
