### ISSUE TITLE
Windows build node

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#54]
Requisition and set up Windows build node

**Comment by eugenwintersberger** [comment]
In principle I could create a build node on Appveyor (I already build h5cpp there with conan) so that we have at least a quick check if things are working correctly. Would this be an acceptable temporary solution to get this ticket out of the way for a release?

**Comment by martukas** [comment]
It actually finally builds! You can go see it here:
https://jenkins.esss.dk/dm/job/h5cpp-windows/
Just on master for now. We will need to integrate this into the Jenkins pipeline script. For this we will need prebuilt conan packages so as the build time would be within reasonable bounds. I will create a separate ticket for this. But we can sort of consider this closed for the milestone.
