### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#55]
Figure out a way to automatically publish generated docs

**Comment by martukas** [comment]
Will be published here: https://ess-dmsc.github.io/h5cpp/

For now it is manually generated, but I'm working on automating this as Jenkins jobs.

**Comment by martukas** [comment]
Created a manual relative link to doxy from the sphinx-generated page on api docs. The big question would be: should we use doxy at all? Apparently sphinx is capable of generating API doc for C++ as well, and from what I've seen its syntax is even somewhat cleaner. Should be perhaps go this way?

**Comment by eugenwintersberger** [comment]
Actually, as far as I know sphinx cannot auto-generate documentation for C++. So my documentation process typically runs in two steps

1. generate XML documentation with `doxygen`
2. use [breathe](https://breathe.readthedocs.io/en/latest/) extension for sphinx to import the API documentation into sphinx.

**Comment by martukas** [comment]
The way I propose this should work is:
whenever a commit is pushed to the master branch, the Jenkins build should generate the documentation via "make html", then pushes the artifacts to the gh-pages branch. The main problems to be solved are:
1) Lack of sphinx on build node. Since we will eventually be building on different nodes, maybe there is a general way of bring in this dependency? Jonas suggested some kind of solution with Docker. Not sure how applicable that is.
2) Need to give Jenkins some kind of github credentials.
3) Need to somehow enforce that only the master branch docs builds get published.
I think eventually we ought to enforce that only released versions get published, not all master builds.

**Comment by martukas** [comment]
The following has been implemented:
1) Sphinx-generated webpage has dote of build, branch and commit hash in the footer, right under the copyright. Layout could be improved.
2) Jenkins pipeline improved:
    a) if branch is master, it checks out the gh-pages branch, copies the generated webpage there and pushes it to repo
    b) if branch is anything else, it archives the generated webpage as Jenkins artifact
3) Experiments subdirectory has been removed, as all relevant tests are now part of ObjectId
