### ISSUE TITLE
Fetching  the catch2 conan package for windows fails

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#551]
I the tests of #501 i.e. https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fh5cpp/detail/pr_501/34/pipeline/34
we get
```
catch2/2.13.7: Not found in local cache, looking in remotes...
catch2/2.13.7: Trying with 'bincrafters'...
WARN: hdf5/1.10.5-dm2@ess-dmsc/stable: requirement zlib/1.2.11@conan/stable overridden by your conanfile to zlib/1.2.11 
ERROR: HTTPSConnectionPool(host='bincrafters.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/public-conan/v1/ping (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:777)'),))

Unable to connect to bincrafters=https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:33 (conan_cmake_run)
```
It looks like fetching conan catch2 packages fails for windows. One solution would be to add it to 
https://artifactoryconan.esss.dk/artifactory/webapp or/and local cache

**Comment by planetmarshall** [comment]
Try updating the conan version on CI. I have observed similar errors when using an outdated conan version (current version is 1.43.1)

Typically on CI I'll run `pip install conan --upgrade` as an initial step to ensure I'm always using the latest version.

**Comment by jkotan** [comment]
Indeed, it looks like https://issueexplorer.com/issue/conan-io/conan/9819 

@zjttoefs , @amues or  @SkyToGround is it possible to upgrade conan on Windows test node?

**Comment by SkyToGround** [comment]
@jkotan It is possible but our expert on the matter (@amues) is away on vacation and I would prefer to have him do it as would be much more work for anyone else to do it.

**Comment by jkotan** [comment]
@

> @jkotan It is possible but our expert on the matter (@amues) is away on vacation and I would prefer to have him do it as would be much more work for anyone else to do it.

@SkyToGround  and @amues, sure. Thanks.

**Comment by jkotan** [comment]
Hi @amues and @SkyToGround,

it looks like windows node does not work anymore
```
Queued   ‘dmbuild04.dm.esss.dk’ is offline
```
https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fh5cpp/detail/issue_568/2/pipeline
Is it related with fixing the issue?

**Comment by amues** [comment]
Hi @jkotan,
I ran into a Jenkins connection issue in that build node after upgrading Conan (I suspect the issue is not related to the upgrade) and I'm currently looking into this.

**Comment by jkotan** [comment]
Due to #570 we can close the issue
