### ISSUE TITLE
examples writin_image buildin fails

### ISSUE THREAD

**Issue by drsramd** [ess-dmsc/h5cpp#564]
linux 20.04
cmake 22.3
gcc 9.3
vscode
lastest master of h5cpp

/usr/local/include/h5cpp/dataspace/type_trait.hpp: In instantiation of ‘const hdf5::dataspace::Dataspace& hdf5::dataspace::get(const T&, hdf5::dataspace::DataspacePool&) [with T = Image<RGBPixel>]’:
[build] /usr/local/include/h5cpp/dataspace/type_trait.hpp:203:38:   required from ‘const hdf5::dataspace::Dataspace& hdf5::dataspace::DataspaceHolder::get(const T&) [with T = Image<RGBPixel>]’
[build] /usr/local/include/h5cpp/node/dataset.hpp:998:3:   required from ‘void hdf5::node::Dataset::write(const T&, const hdf5::property::DatasetTransferList&) [with T = Image<RGBPixel>]’
[build] /home/arno/Platform/playCPP/playH5Cpp/writing_image.cpp:50:22:   required from here
[build] /usr/local/include/h5cpp/dataspace/type_trait.hpp:150:27: error: no matching function for call to ‘hdf5::dataspace::TypeTrait<Image<RGBPixel> >::get(const Image<RGBPixel>&, hdf5::dataspace::DataspacePool&)’
[build]   150 |   return TypeTrait<T>::get(value, pool);
[build]       |          ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

In file included from /home/arno/Platform/playCPP/playH5Cpp/writing_image.cpp:30:
[build] /home/arno/Platform/playCPP/playH5Cpp/image_h5.hpp:71:34: note: candidate: ‘static const DataspaceType& hdf5::dataspace::TypeTrait<Image<PixelT> >::get(const Image<PixelT>&) [with PixelT = RGBPixel; hdf5::dataspace::TypeTrait<Image<PixelT> >::DataspaceType = hdf5::dataspace::Simple]’
[build]    71 |     const static DataspaceType & get(const Image<PixelT> &value)

image_h5.hpp:71:34: note:   candidate expects 1 argument, 2 provided
[build] ninja: build stopped: subcommand failed.

**Comment by jkotan** [comment]
Hi @drsramd,  
it looks like you use the latest (master) version of h5cpp which is not released yet.
In order to make it work you need to add  to your `dataspace::TypTrait<Image>:: get(...)` in image_h5.hpp a second argument (`DataspacePool&`). i.e.
```c++
hdf5::dataspace::TypeTrait<Image >::get(const Image&,hdf5::dataspace::DataspacePool& )
```
If it does not work to help you I would need to see your TypeTrait<Image> implementation.

**Comment by drsramd** [comment]
Thank you very much - worked;
Would you have some time to explain the meaning of hdf5::dataspace::DataspacePool&?
Under which circumstances does this have to be passed?
The other examples compiled w/o it;

**Comment by jkotan** [comment]
The `hdf5::dataspace::DataspacePool&`  is used to cache used dataspaces in the current Dataset object. 
It was added to speed up writing small chunks of data.
Currently it is used to store only one dimension Simple objects but I think it would be good idea to make it more general.
Using it you don't have to create a Dataspace object for each append data.
For larger chunks of data e.g. image it is not so important i.e. time of writing data is much bigger than time of creating the dataspace object.
Let me know if you have more questions or  you would like to extend the DataspacePool functionality.

**Comment by drsramd** [comment]
Thanks for your kind answer; I am flattered, but you overestimate my capabilities as a programmer ...
I am struggling to understand it, and sadly I am not competent to create / extend any of it;
