### ISSUE TITLE
Refactor coverage compile options

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#57]
I thought to file this as an enhancement, but it looks like the way it's set up now, it actually prevents it from compiling on OSX. So everything to do with coverage should be a CMake option.

**Comment by martukas** [comment]
Building unit tests should be a separate target from building the library, so that
A) The library can be built by the end user without unit tests
B) Building unit tests can be a separate step in Jenkins

**Comment by SkyToGround** [comment]
There are improvements to the build system that could be made but I consider this to issue to closed for now.
