### ISSUE TITLE
Iterator tests

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#58]
Base iterator class is missing tests for most functions, also has warnings.

**Comment by martukas** [comment]
1) Iterator::index_ does not have default value, making default constructor behavior undefined. Should it be 0?
2) There is no equals comparison operator. Should there be?

**Comment by eugenwintersberger** [comment]
1. I guess setting the default value of the iterator to 0 is ok
2. definitely a good idea
