### ISSUE TITLE
LZO compression

### ISSUE THREAD

**Issue by ramezquitao** [ess-dmsc/h5cpp#597]
First of all, I would like to thanks the authors for this library. It is really helpful and simple to use.

I have some data saved using pytables. My programs use LZO compression in pytables. When trying to open this files using h5cpp, I get an error saying the LZO filter is not registered. I find it quite strange because the pytables (vitables for example) running in the same computer can open the files, meaning the low level libraries can open the file even it is LZO compressed. I know I can convert the files using ptrepack, but I would prefer using the files as they are. Can some one point me in the correct direction to enable the LZO support in h5cpp?

Thanks

**Comment by jkotan** [comment]
Hi @ramezquitao, 
Usually the hdf5 filters are deployed separately to libhdf5 (as well as libh5cpp).
It can be downloaded from

    https://www.hdfgroup.org/packages/hdf5-1120-filter-plugins/
    https://github.com/nexusformat/HDF5-External-Filter-Plugins

or deb packages

    http://repos.pni-hdri.de/apt/debian/incoming/hdf5-external-filter-plugins-static/
    http://repos.pni-hdri.de/apt/debian/incoming/hdf5-external-filter-plugins/

To make filters  visible by the libhdf5 library one need to install them (e.g. filter .so libraries) at `HDF5_PLUGIN_PATH`,
i.e. debian-like system it is `/usr/lib/x86_64-linux-gnu/hdf5/plugins` or `/usr/lib/x86_64-linux-gnu/hdf5/serial/plugins`

Unfortunately, to my knowledge the LZO hdf5 filter is only defined in pytables (merged into pytable cython libraries).

So one way is to split it from pytables, create a separate filter library and place it into your HDF5_PLUGIN_PATH directory.

Other option is to ask HDFgroup to support the LZO filter i.e. as to provide it via https://www.hdfgroup.org/packages 
(There will be an HDFgroup meeting in ITER at the end of this week)

**Comment by ramezquitao** [comment]
@jkotan thanks for the info. I already have the filter's deb installed, and as you say, I can not use LZO. I will write to the hdf support group to see if I can get help there, or maybe check pytables source-code to see if I can do something myself. 
For the moment I will close the issue, thanks.
