### ISSUE TITLE
Is there a reason for setting sphinx==4.0.3 in the Jenkinsfile for building the documentation?

### ISSUE THREAD

**Issue by amues** [ess-dmsc/h5cpp#607]
@eugenwintersberger @jkotan @yuelongyu

Do we have a specific reason for this? I'm updating the Jenkinsbuild to use a more recent version of Ubuntu (22.04), and that version of Sphinx fails when running `make html`. Would it be ok to use version 5?

**Comment by yuelongyu** [comment]
Hi @amues,  @jkotan mentioned that sphinx, breathe and doxygen do not work with each other when they are installed from pip and conan. That's the reason why it's set to 4.0.3 (#499 ).

If version 5 fixes the issue, I think it's reasonable to upgrade it.

**Comment by amues** [comment]
@yuelongyu thanks for the quick reply! I've added the sphinx and breathe installation to our build node Docker image, so we don't need to install them as part of the Jenkins build. I used the latest version less than 5.
