### ISSUE TITLE
DEB package generation

### ISSUE THREAD

**Issue by ramezquitao** [ess-dmsc/h5cpp#636]
I just installed Debian 12 bookworm, and it seems you don't have debs for this distro yet. Can you point me to some instructions to generate the deb package for your library.

Thanks

**Comment by jkotan** [comment]
Hi @ramezquitao,
the bookworm will be released on 2023-06-10 so I will build the debian12 packages soon. 

To build the debian packages I use gpb on https://gitlab.desy.de/petra-iii-debian-packages/h5cpp and my pidptools scripts available in our HDRI repository.

**Comment by jkotan** [comment]
I've just run my scripts and created testing h5cpp packages for bookworm and put them to the HDRI repository. 
I've also added  http://repos.pni-hdri.de/bookworm-pni-hdri.list
More tests and package verification will be done after the release.

**Comment by ramezquitao** [comment]
Thanks. I will close the issue for the moment
