### ISSUE TITLE
ssize_t unknown in macOS clang 15.0.0 build

### ISSUE THREAD

**Issue by amues** [ess-dmsc/h5cpp#651]
Identified by @mortenjc:
```
In file included from (...)/h5cpp/src/h5cpp/core/iterator.cpp:26:
(...)/h5cpp/src/h5cpp/core/iterator.hpp:36:5: error: unknown type name 'ssize_t'; did you mean 'size_t'?
```

**Comment by jkotan** [comment]
Hi @amues,
The `ssize_t`  a type defined by POSIX so if someone use pure C it is not defined.  We have a workaround for windows 
```
#ifdef _MSC_VER
#if defined _M_IX86
    using ssize_t = int;
#elif defined _M_X64
    #include <BaseTsd.h>
    using ssize_t = SSIZE_T;
#endif
#endif
```
We could do a simialar tricks for non-POSIX compilers.

**Comment by jkotan** [comment]
is it fixed by https://github.com/ess-dmsc/h5cpp/commit/9486a26225b4369ebf8540bc9cce93efabe38917 ?
