### ISSUE TITLE
Modify copy constructors for Dataspace

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#68]
This is a subticket for #1

**Comment by martukas** [comment]
Do we even need a default constructors for abstract Dataspace? Abstract Datatype doesn't have one, and if it's a null type, throwing exceptions on all getters, it was constructed from an invalid hid, which should not have happened in the first place? I haven't thought this through completely, so please look at the actual code to consider the implications.

**Comment by martukas** [comment]
I see the answer to the previous question in some of the header documentation. Default constructor is "necessary for using a Datatype with certain C++ STL containers." Sounds good. Another question, though: Dataspace has a 
```
bool valid() const;
```
function. Should Datatype and other have these too? This is just a wrapper that confirms the validity of hid. Should it actually check something specific to the Class?

**Comment by martukas** [comment]
Do we need equality comparison operators for Dataspace? H5 defines H5Sextent_equal, which is not quite the same, but perhaps ticket-worthy nonetheless?

**Comment by eugenwintersberger** [comment]
I have added an `is_valid` method to the `Datatype` class in my current work on the `Array` type. So this is already covered.

Concerning the equality check for dataspaces: I do not see a big reason to implement this. But we maybe can discuss this in one of the latter hangouts to setup some use cases.
