### ISSUE TITLE
Implementation of == and != operator for hdf5::node::Node

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/h5cpp#7]
As we have now a working ID implementation we could use this to implement the operators

```cpp
bool operator==(const hdf5::node::Node &lhs,const hdf5::node::Node &rhs);
bool operator!=(const hdf5::node::Node &lhs,const hdf5::node::Node &rhs);
```
The implementation should be straight forward using the ```id()``` member method.

**Comment by martukas** [comment]
Implemented, as well as some tests for the Node class.
The comparison test is kind of trivial for now, as there are no fixtures for meaningfully different Nodes.
I guess we can close this nonetheless, and we'll have other tickets for test coverage & quality.
