### ISSUE TITLE
String/0.VariableIO unit test crashes

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#76]
The String/0.VariableIO unit test (defined in *test/datatype/string_test.cpp*) crashes the unit test application with a *EXC_BAD_ACCESS* error. This occurs on MacOSX using the Clang compiler.

The error appears to be caused by the line:
```c++
a.write(this->value_);
```

Which in turn causes the error to happen in the following line (line 114 of attribute.hpp):
```c++
if(H5Awrite(static_cast<hid_t>(handle_),static_cast<hid_t>(type),ptr)<0)
```

**Comment by eugenwintersberger** [comment]
I would remove this for the moment as it is not implemented. Working on this.

**Comment by eugenwintersberger** [comment]
Is this bug still an issue though we have now reasonable String IO available?

**Comment by SkyToGround** [comment]
Well, I did not look into what the test actually did or what it tested. I simply consider a crashing or failing test a bug. Thus I leave it up to you to decide if this issue can be closed.

**Comment by martukas** [comment]
Well, we don't have a common OSX environment that we test on (yet). So maybe you could try to reproduce it on the same system with the latest commit?

**Comment by eugenwintersberger** [comment]
I go with Martin in this case. That's most probably the best approach to get rid of this ticket.

**Comment by eugenwintersberger** [comment]
When do you guys think we get some confirmation on this issue?

**Comment by SkyToGround** [comment]
When comparing the names of the unit tests, this particular unit test is now gone and presumably replaced with another one. The unit test executable no longer crashes on MacOSX. I will thus close this issue.
