### ISSUE TITLE
Invalid pointer when running unit tests under Ubuntu 16.04

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/h5cpp#77]
Running the unit tests under Ubuntu 16.04 results in a invalid pointer core dump when attempting to execute some of the unit tests in the group "ObjectId" (I have only tested ObjectId.hard_group and ObjectId.hard_dset). Note that builds where this was tested were using HDF5 and boost libraries provided by Conan.

To reproduce, run:
```bash
bin/unit_tests --gtest_filter=ObjectId.hard_group
#or
bin/unit_tests --gtest_filter=ObjectId.hard_dset
```
The output from the run is attached.

I can consider looking into the issue but I thought I would show it to you first in case you have a good idea of what the cause is.

[core_dump.txt](https://github.com/ess-dmsc/h5cpp/files/1407941/core_dump.txt)

**Comment by eugenwintersberger** [comment]
Does this failure also occur when using the system libraries?

**Comment by SkyToGround** [comment]
Well, the short answer is yes.

However, when running with dependencies not installed by conan I do not get the core dump information and the core dump occurs at the end of the test run. The output is:
```bash
<snip>
[----------] Global test environment tear-down
[==========] 249 tests from 72 test cases ran. (459 ms total)
[  PASSED  ] 249 tests.
Segmentation fault (core dumped)
```

However, the problem is still probably caused by the *ObjectId* tests as excluding those tests (``bin/unit_tests --gtest_filter=-ObjectId.*``) results in no core dump:
```bash
<snip>
[----------] Global test environment tear-down
[==========] 239 tests from 71 test cases ran. (363 ms total)
[  PASSED  ] 239 tests.
```

Whereas running only the ObjectId.hard_dset test does result in a core dump:
```bash
vagrant@vagrant:~/shared/h5cpp/build_linux$ bin/unit_tests --gtest_filter=ObjectId.hard_dset
Note: Google Test filter = ObjectId.hard_dset
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ObjectId
<snip>
[       OK ] ObjectId.hard_dset (8 ms)
[----------] 1 test from ObjectId (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9 ms total)
[  PASSED  ] 1 test.
Segmentation fault (core dumped)
```

**Comment by martukas** [comment]
This is weird, because I have: Ubuntu 16.04.3 LTS
Not seeing the same problem.

**Comment by SkyToGround** [comment]
There is some indication that this might be related to the version of one of the libraries in use. Regardless, I do not feel a strong urge to debug this problem at the moment so I suggest we leave it for now.

**Comment by eugenwintersberger** [comment]
I will have a look on this today.

**Comment by eugenwintersberger** [comment]
I cannot reproduce the problem with system libraries.

**Comment by martukas** [comment]
I propose we don't report issues that cannot be reproduced on Jenkins. Once we containerize our builds, we can set up a Ubuntu node, and then if such things come out of the woodwork, we can open tickets for them.
