### ISSUE TITLE
Clang format

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#82]
Configure Clang format to follow the google style guide and ensure consistent formatting

**Comment by eugenwintersberger** [comment]
Could we wait with the big formatting party until we have a first alpha release.

**Comment by martukas** [comment]
Hahaha. Ok :)
I'll remove it from the milestone. But I might get around doing this anyway just to see how/if it works. I don't suggest that we necessarily start automating its enforcement or anything like that.
